package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Alert generated by hbm2java
 */
@Entity
@Table(name = "alert", catalog = "induct")
public class Alert implements java.io.Serializable {

	private Integer id;
	private TypeAlert typeAlert;
	private StatusAlert statusAlert;
	private Cattle cattle;
	private Member member;
	private String cattle_1;
	private String note;
	private String datealert;
	private String timealert;
	private String dayinput;
	private String timeinput;

	public Alert() {
	}

	public Alert(TypeAlert typeAlert, StatusAlert statusAlert, Cattle cattle, Member member, String cattle_1,
			String note, String datealert, String timealert, String dayinput, String timeinput) {
		this.typeAlert = typeAlert;
		this.statusAlert = statusAlert;
		this.cattle = cattle;
		this.member = member;
		this.cattle_1 = cattle_1;
		this.note = note;
		this.datealert = datealert;
		this.timealert = timealert;
		this.dayinput = dayinput;
		this.timeinput = timeinput;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_alert_id")
	public TypeAlert getTypeAlert() {
		return this.typeAlert;
	}

	public void setTypeAlert(TypeAlert typeAlert) {
		this.typeAlert = typeAlert;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_alert_id")
	public StatusAlert getStatusAlert() {
		return this.statusAlert;
	}

	public void setStatusAlert(StatusAlert statusAlert) {
		this.statusAlert = statusAlert;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cattle_id")
	public Cattle getCattle() {
		return this.cattle;
	}

	public void setCattle(Cattle cattle) {
		this.cattle = cattle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "cattle", length = 45)
	public String getCattle_1() {
		return this.cattle_1;
	}

	public void setCattle_1(String cattle_1) {
		this.cattle_1 = cattle_1;
	}

	@Column(name = "note", length = 100)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "datealert", length = 10)
	public String getDatealert() {
		return this.datealert;
	}

	public void setDatealert(String datealert) {
		this.datealert = datealert;
	}


	@Column(name = "timealert", length = 8)
	public String getTimealert() {
		return this.timealert;
	}

	public void setTimealert(String timealert) {
		this.timealert = timealert;
	}

	@Column(name = "dayinput", length = 10)
	public String getDayinput() {
		return this.dayinput;
	}

	public void setDayinput(String dayinput) {
		this.dayinput = dayinput;
	}

	@Column(name = "timeinput", length = 8)
	public String getTimeinput() {
		return this.timeinput;
	}

	public void setTimeinput(String timeinput) {
		this.timeinput = timeinput;
	}

}
