// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * Alert generated by hbm2java
 */
public class Alert  implements java.io.Serializable {


     private Integer id;
     private Cattle cattle;
     private Member member;
     private StatusAlert statusAlert;
     private TypeAlert typeAlert;
     private String cattle_1;
     private String note;
     private Date datealert;
     private Date timealert;
     private Date dayinput;
     private Date timeinput;

    public Alert() {
    }

    public Alert(Cattle cattle, Member member, StatusAlert statusAlert, TypeAlert typeAlert, String cattle_1, String note, Date datealert, Date timealert, Date dayinput, Date timeinput) {
       this.cattle = cattle;
       this.member = member;
       this.statusAlert = statusAlert;
       this.typeAlert = typeAlert;
       this.cattle_1 = cattle_1;
       this.note = note;
       this.datealert = datealert;
       this.timealert = timealert;
       this.dayinput = dayinput;
       this.timeinput = timeinput;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cattle getCattle() {
        return this.cattle;
    }
    
    public void setCattle(Cattle cattle) {
        this.cattle = cattle;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public StatusAlert getStatusAlert() {
        return this.statusAlert;
    }
    
    public void setStatusAlert(StatusAlert statusAlert) {
        this.statusAlert = statusAlert;
    }
    public TypeAlert getTypeAlert() {
        return this.typeAlert;
    }
    
    public void setTypeAlert(TypeAlert typeAlert) {
        this.typeAlert = typeAlert;
    }
    public String getCattle_1() {
        return this.cattle_1;
    }
    
    public void setCattle_1(String cattle_1) {
        this.cattle_1 = cattle_1;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Date getDatealert() {
        return this.datealert;
    }
    
    public void setDatealert(Date datealert) {
        this.datealert = datealert;
    }
    public Date getTimealert() {
        return this.timealert;
    }
    
    public void setTimealert(Date timealert) {
        this.timealert = timealert;
    }
    public Date getDayinput() {
        return this.dayinput;
    }
    
    public void setDayinput(Date dayinput) {
        this.dayinput = dayinput;
    }
    public Date getTimeinput() {
        return this.timeinput;
    }
    
    public void setTimeinput(Date timeinput) {
        this.timeinput = timeinput;
    }




}


