// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bill generated by hbm2java
 */
public class Bill  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private StatusBill statusBill;
     private TypeBill typeBill;
     private Integer idbill;
     private Date day;
     private Set toolBrokens = new HashSet(0);

    public Bill() {
    }

	
    public Bill(Member member, StatusBill statusBill, TypeBill typeBill) {
        this.member = member;
        this.statusBill = statusBill;
        this.typeBill = typeBill;
    }
    public Bill(Member member, StatusBill statusBill, TypeBill typeBill, Integer idbill, Date day, Set toolBrokens) {
       this.member = member;
       this.statusBill = statusBill;
       this.typeBill = typeBill;
       this.idbill = idbill;
       this.day = day;
       this.toolBrokens = toolBrokens;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public StatusBill getStatusBill() {
        return this.statusBill;
    }
    
    public void setStatusBill(StatusBill statusBill) {
        this.statusBill = statusBill;
    }
    public TypeBill getTypeBill() {
        return this.typeBill;
    }
    
    public void setTypeBill(TypeBill typeBill) {
        this.typeBill = typeBill;
    }
    public Integer getIdbill() {
        return this.idbill;
    }
    
    public void setIdbill(Integer idbill) {
        this.idbill = idbill;
    }
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }
    public Set getToolBrokens() {
        return this.toolBrokens;
    }
    
    public void setToolBrokens(Set toolBrokens) {
        this.toolBrokens = toolBrokens;
    }




}


