// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Breeding generated by hbm2java
 */
public class Breeding  implements java.io.Serializable {


     private Integer id;
     private Cattle cattleByCattlemaId;
     private Cattle cattleByCattlefaId;
     private CountBreed countBreed;
     private Member member;
     private Semen semen;
     private Date stillTime;
     private Date dateTime;
     private String amount;
     private String note;
     private String statusCattle;
     private Set pregnants = new HashSet(0);

    public Breeding() {
    }

    public Breeding(Cattle cattleByCattlemaId, Cattle cattleByCattlefaId, CountBreed countBreed, Member member, Semen semen, Date stillTime, Date dateTime, String amount, String note, String statusCattle, Set pregnants) {
       this.cattleByCattlemaId = cattleByCattlemaId;
       this.cattleByCattlefaId = cattleByCattlefaId;
       this.countBreed = countBreed;
       this.member = member;
       this.semen = semen;
       this.stillTime = stillTime;
       this.dateTime = dateTime;
       this.amount = amount;
       this.note = note;
       this.statusCattle = statusCattle;
       this.pregnants = pregnants;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cattle getCattleByCattlemaId() {
        return this.cattleByCattlemaId;
    }
    
    public void setCattleByCattlemaId(Cattle cattleByCattlemaId) {
        this.cattleByCattlemaId = cattleByCattlemaId;
    }
    public Cattle getCattleByCattlefaId() {
        return this.cattleByCattlefaId;
    }
    
    public void setCattleByCattlefaId(Cattle cattleByCattlefaId) {
        this.cattleByCattlefaId = cattleByCattlefaId;
    }
    public CountBreed getCountBreed() {
        return this.countBreed;
    }
    
    public void setCountBreed(CountBreed countBreed) {
        this.countBreed = countBreed;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Semen getSemen() {
        return this.semen;
    }
    
    public void setSemen(Semen semen) {
        this.semen = semen;
    }
    public Date getStillTime() {
        return this.stillTime;
    }
    
    public void setStillTime(Date stillTime) {
        this.stillTime = stillTime;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getStatusCattle() {
        return this.statusCattle;
    }
    
    public void setStatusCattle(String statusCattle) {
        this.statusCattle = statusCattle;
    }
    public Set getPregnants() {
        return this.pregnants;
    }
    
    public void setPregnants(Set pregnants) {
        this.pregnants = pregnants;
    }




}


