// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bucket generated by hbm2java
 */
public class Bucket  implements java.io.Serializable {


     private Integer id;
     private TypeBucket typeBucket;
     private String code;
     private String number;
     private String name;
     private String brand;
     private String size;
     private Float weightnull;
     private Float weightfull;
     private Float diaPartition;
     private Float diaBody;
     private Float heightBody;
     private Float ratioNitrogen;
     private Integer periodNitrogen;
     private String goblet;
     private Float diaCanister;
     private Float heightCanister;
     private Integer quantityCanister;
     private Float containPerC;
     private Date dayInN;
     private Date dayExpN;
     private Date dayImport;
     private String import_;
     private String place;
     private int statusalert;
     private Set semens = new HashSet(0);

    public Bucket() {
    }

	
    public Bucket(int statusalert) {
        this.statusalert = statusalert;
    }
    public Bucket(TypeBucket typeBucket, String code, String number, String name, String brand, String size, Float weightnull, Float weightfull, Float diaPartition, Float diaBody, Float heightBody, Float ratioNitrogen, Integer periodNitrogen, String goblet, Float diaCanister, Float heightCanister, Integer quantityCanister, Float containPerC, Date dayInN, Date dayExpN, Date dayImport, String import_, String place, int statusalert, Set semens) {
       this.typeBucket = typeBucket;
       this.code = code;
       this.number = number;
       this.name = name;
       this.brand = brand;
       this.size = size;
       this.weightnull = weightnull;
       this.weightfull = weightfull;
       this.diaPartition = diaPartition;
       this.diaBody = diaBody;
       this.heightBody = heightBody;
       this.ratioNitrogen = ratioNitrogen;
       this.periodNitrogen = periodNitrogen;
       this.goblet = goblet;
       this.diaCanister = diaCanister;
       this.heightCanister = heightCanister;
       this.quantityCanister = quantityCanister;
       this.containPerC = containPerC;
       this.dayInN = dayInN;
       this.dayExpN = dayExpN;
       this.dayImport = dayImport;
       this.import_ = import_;
       this.place = place;
       this.statusalert = statusalert;
       this.semens = semens;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TypeBucket getTypeBucket() {
        return this.typeBucket;
    }
    
    public void setTypeBucket(TypeBucket typeBucket) {
        this.typeBucket = typeBucket;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public Float getWeightnull() {
        return this.weightnull;
    }
    
    public void setWeightnull(Float weightnull) {
        this.weightnull = weightnull;
    }
    public Float getWeightfull() {
        return this.weightfull;
    }
    
    public void setWeightfull(Float weightfull) {
        this.weightfull = weightfull;
    }
    public Float getDiaPartition() {
        return this.diaPartition;
    }
    
    public void setDiaPartition(Float diaPartition) {
        this.diaPartition = diaPartition;
    }
    public Float getDiaBody() {
        return this.diaBody;
    }
    
    public void setDiaBody(Float diaBody) {
        this.diaBody = diaBody;
    }
    public Float getHeightBody() {
        return this.heightBody;
    }
    
    public void setHeightBody(Float heightBody) {
        this.heightBody = heightBody;
    }
    public Float getRatioNitrogen() {
        return this.ratioNitrogen;
    }
    
    public void setRatioNitrogen(Float ratioNitrogen) {
        this.ratioNitrogen = ratioNitrogen;
    }
    public Integer getPeriodNitrogen() {
        return this.periodNitrogen;
    }
    
    public void setPeriodNitrogen(Integer periodNitrogen) {
        this.periodNitrogen = periodNitrogen;
    }
    public String getGoblet() {
        return this.goblet;
    }
    
    public void setGoblet(String goblet) {
        this.goblet = goblet;
    }
    public Float getDiaCanister() {
        return this.diaCanister;
    }
    
    public void setDiaCanister(Float diaCanister) {
        this.diaCanister = diaCanister;
    }
    public Float getHeightCanister() {
        return this.heightCanister;
    }
    
    public void setHeightCanister(Float heightCanister) {
        this.heightCanister = heightCanister;
    }
    public Integer getQuantityCanister() {
        return this.quantityCanister;
    }
    
    public void setQuantityCanister(Integer quantityCanister) {
        this.quantityCanister = quantityCanister;
    }
    public Float getContainPerC() {
        return this.containPerC;
    }
    
    public void setContainPerC(Float containPerC) {
        this.containPerC = containPerC;
    }
    public Date getDayInN() {
        return this.dayInN;
    }
    
    public void setDayInN(Date dayInN) {
        this.dayInN = dayInN;
    }
    public Date getDayExpN() {
        return this.dayExpN;
    }
    
    public void setDayExpN(Date dayExpN) {
        this.dayExpN = dayExpN;
    }
    public Date getDayImport() {
        return this.dayImport;
    }
    
    public void setDayImport(Date dayImport) {
        this.dayImport = dayImport;
    }
    public String getImport_() {
        return this.import_;
    }
    
    public void setImport_(String import_) {
        this.import_ = import_;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    public int getStatusalert() {
        return this.statusalert;
    }
    
    public void setStatusalert(int statusalert) {
        this.statusalert = statusalert;
    }
    public Set getSemens() {
        return this.semens;
    }
    
    public void setSemens(Set semens) {
        this.semens = semens;
    }




}


