// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * CableDisease generated by hbm2java
 */
public class CableDisease  implements java.io.Serializable {


     private Integer id;
     private String value;
     private Set diseases = new HashSet(0);

    public CableDisease() {
    }

    public CableDisease(String value, Set diseases) {
       this.value = value;
       this.diseases = diseases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set getDiseases() {
        return this.diseases;
    }
    
    public void setDiseases(Set diseases) {
        this.diseases = diseases;
    }




}


