// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * CattleDetail generated by hbm2java
 */
public class CattleDetail  implements java.io.Serializable {


     private Integer id;
     private Cattle cattle;
     private FormulaRecord formulaRecord;
     private Date date;
     private Integer age;
     private Float weight;
     private Float wpD;
     private Float pregnant;
     private Integer lactation;
     private Float lactationPerDays;
     private Float fatMilk;
     private String unitBond;
     private String typeEating;
     private String strain;
     private String unitEnergy;
     private String stageWalk;
     private String priceMilk;
     private String scoreBody;

    public CattleDetail() {
    }

    public CattleDetail(Cattle cattle, FormulaRecord formulaRecord, Date date, Integer age, Float weight, Float wpD, Float pregnant, Integer lactation, Float lactationPerDays, Float fatMilk, String unitBond, String typeEating, String strain, String unitEnergy, String stageWalk, String priceMilk, String scoreBody) {
       this.cattle = cattle;
       this.formulaRecord = formulaRecord;
       this.date = date;
       this.age = age;
       this.weight = weight;
       this.wpD = wpD;
       this.pregnant = pregnant;
       this.lactation = lactation;
       this.lactationPerDays = lactationPerDays;
       this.fatMilk = fatMilk;
       this.unitBond = unitBond;
       this.typeEating = typeEating;
       this.strain = strain;
       this.unitEnergy = unitEnergy;
       this.stageWalk = stageWalk;
       this.priceMilk = priceMilk;
       this.scoreBody = scoreBody;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cattle getCattle() {
        return this.cattle;
    }
    
    public void setCattle(Cattle cattle) {
        this.cattle = cattle;
    }
    public FormulaRecord getFormulaRecord() {
        return this.formulaRecord;
    }
    
    public void setFormulaRecord(FormulaRecord formulaRecord) {
        this.formulaRecord = formulaRecord;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public Float getWeight() {
        return this.weight;
    }
    
    public void setWeight(Float weight) {
        this.weight = weight;
    }
    public Float getWpD() {
        return this.wpD;
    }
    
    public void setWpD(Float wpD) {
        this.wpD = wpD;
    }
    public Float getPregnant() {
        return this.pregnant;
    }
    
    public void setPregnant(Float pregnant) {
        this.pregnant = pregnant;
    }
    public Integer getLactation() {
        return this.lactation;
    }
    
    public void setLactation(Integer lactation) {
        this.lactation = lactation;
    }
    public Float getLactationPerDays() {
        return this.lactationPerDays;
    }
    
    public void setLactationPerDays(Float lactationPerDays) {
        this.lactationPerDays = lactationPerDays;
    }
    public Float getFatMilk() {
        return this.fatMilk;
    }
    
    public void setFatMilk(Float fatMilk) {
        this.fatMilk = fatMilk;
    }
    public String getUnitBond() {
        return this.unitBond;
    }
    
    public void setUnitBond(String unitBond) {
        this.unitBond = unitBond;
    }
    public String getTypeEating() {
        return this.typeEating;
    }
    
    public void setTypeEating(String typeEating) {
        this.typeEating = typeEating;
    }
    public String getStrain() {
        return this.strain;
    }
    
    public void setStrain(String strain) {
        this.strain = strain;
    }
    public String getUnitEnergy() {
        return this.unitEnergy;
    }
    
    public void setUnitEnergy(String unitEnergy) {
        this.unitEnergy = unitEnergy;
    }
    public String getStageWalk() {
        return this.stageWalk;
    }
    
    public void setStageWalk(String stageWalk) {
        this.stageWalk = stageWalk;
    }
    public String getPriceMilk() {
        return this.priceMilk;
    }
    
    public void setPriceMilk(String priceMilk) {
        this.priceMilk = priceMilk;
    }
    public String getScoreBody() {
        return this.scoreBody;
    }
    
    public void setScoreBody(String scoreBody) {
        this.scoreBody = scoreBody;
    }




}


