// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * CattlePedigree generated by hbm2java
 */
public class CattlePedigree  implements java.io.Serializable {


     private Integer id;
     private Cattle cattle;
     private Farm farm;
     private TypeCattle typeCattle;
     private TypeClassBeef typeClassBeef;
     private TypeClassDairy typeClassDairy;
     private String ma;
     private String docility;
     private String tenderness;
     private String breastFront;
     private String breastBack;
     private String breastBackHeight;
     private String breastBackWidth;
     private String breastDepth;
     private String lenthNipple;
     private String frontBreast;
     private String backBreast;
     private String body;
     private String bodyDepth;
     private String stong;
     private String hipAngle;
     private String widthHips;
     private String curBackLegs;
     private String straightBackLegs;
     private String hoofCorner;
     private String pointLegHoof;
     private String ageYield;
     private String milk;
     private String protein;
     private String fat;
     private String netIncome;
     private String birthRate;
     private String daughterBirthRate;
     private String firstDeath;
     private String daughterFirstDeath;
     private String daughterPregnancyRate;
     private String somatic;
     private String tm;
     private String sc;
     private String rea;
     private String imf;
     private String rump;
     private String adg;
     private String calvingEaseDir;
     private String calvingEaseDtrs;
     private String gestationLength;
     private String 200dayWt;
     private String 400dayWt;
     private String 600dayWt;
     private String matCow;
     private String 200dayMilk;
     private String scrotalSize;
     private String carcaseWt;
     private String eyeMuscleArea;
     private String ribFat;
     private String retailBeefYield;
     private String ebv;
     private String acc;
     private String price;
     private String priceStart;
     private String priceEnd;
     private String dateReport;
     private String picture;
     private String numberEar;
     private Set cattles = new HashSet(0);

    public CattlePedigree() {
    }

    public CattlePedigree(Cattle cattle, Farm farm, TypeCattle typeCattle, TypeClassBeef typeClassBeef, TypeClassDairy typeClassDairy, String ma, String docility, String tenderness, String breastFront, String breastBack, String breastBackHeight, String breastBackWidth, String breastDepth, String lenthNipple, String frontBreast, String backBreast, String body, String bodyDepth, String stong, String hipAngle, String widthHips, String curBackLegs, String straightBackLegs, String hoofCorner, String pointLegHoof, String ageYield, String milk, String protein, String fat, String netIncome, String birthRate, String daughterBirthRate, String firstDeath, String daughterFirstDeath, String daughterPregnancyRate, String somatic, String tm, String sc, String rea, String imf, String rump, String adg, String calvingEaseDir, String calvingEaseDtrs, String gestationLength, String 200dayWt, String 400dayWt, String 600dayWt, String matCow, String 200dayMilk, String scrotalSize, String carcaseWt, String eyeMuscleArea, String ribFat, String retailBeefYield, String ebv, String acc, String price, String priceStart, String priceEnd, String dateReport, String picture, String numberEar, Set cattles) {
       this.cattle = cattle;
       this.farm = farm;
       this.typeCattle = typeCattle;
       this.typeClassBeef = typeClassBeef;
       this.typeClassDairy = typeClassDairy;
       this.ma = ma;
       this.docility = docility;
       this.tenderness = tenderness;
       this.breastFront = breastFront;
       this.breastBack = breastBack;
       this.breastBackHeight = breastBackHeight;
       this.breastBackWidth = breastBackWidth;
       this.breastDepth = breastDepth;
       this.lenthNipple = lenthNipple;
       this.frontBreast = frontBreast;
       this.backBreast = backBreast;
       this.body = body;
       this.bodyDepth = bodyDepth;
       this.stong = stong;
       this.hipAngle = hipAngle;
       this.widthHips = widthHips;
       this.curBackLegs = curBackLegs;
       this.straightBackLegs = straightBackLegs;
       this.hoofCorner = hoofCorner;
       this.pointLegHoof = pointLegHoof;
       this.ageYield = ageYield;
       this.milk = milk;
       this.protein = protein;
       this.fat = fat;
       this.netIncome = netIncome;
       this.birthRate = birthRate;
       this.daughterBirthRate = daughterBirthRate;
       this.firstDeath = firstDeath;
       this.daughterFirstDeath = daughterFirstDeath;
       this.daughterPregnancyRate = daughterPregnancyRate;
       this.somatic = somatic;
       this.tm = tm;
       this.sc = sc;
       this.rea = rea;
       this.imf = imf;
       this.rump = rump;
       this.adg = adg;
       this.calvingEaseDir = calvingEaseDir;
       this.calvingEaseDtrs = calvingEaseDtrs;
       this.gestationLength = gestationLength;
       this.200dayWt = 200dayWt;
       this.400dayWt = 400dayWt;
       this.600dayWt = 600dayWt;
       this.matCow = matCow;
       this.200dayMilk = 200dayMilk;
       this.scrotalSize = scrotalSize;
       this.carcaseWt = carcaseWt;
       this.eyeMuscleArea = eyeMuscleArea;
       this.ribFat = ribFat;
       this.retailBeefYield = retailBeefYield;
       this.ebv = ebv;
       this.acc = acc;
       this.price = price;
       this.priceStart = priceStart;
       this.priceEnd = priceEnd;
       this.dateReport = dateReport;
       this.picture = picture;
       this.numberEar = numberEar;
       this.cattles = cattles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cattle getCattle() {
        return this.cattle;
    }
    
    public void setCattle(Cattle cattle) {
        this.cattle = cattle;
    }
    public Farm getFarm() {
        return this.farm;
    }
    
    public void setFarm(Farm farm) {
        this.farm = farm;
    }
    public TypeCattle getTypeCattle() {
        return this.typeCattle;
    }
    
    public void setTypeCattle(TypeCattle typeCattle) {
        this.typeCattle = typeCattle;
    }
    public TypeClassBeef getTypeClassBeef() {
        return this.typeClassBeef;
    }
    
    public void setTypeClassBeef(TypeClassBeef typeClassBeef) {
        this.typeClassBeef = typeClassBeef;
    }
    public TypeClassDairy getTypeClassDairy() {
        return this.typeClassDairy;
    }
    
    public void setTypeClassDairy(TypeClassDairy typeClassDairy) {
        this.typeClassDairy = typeClassDairy;
    }
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }
    public String getDocility() {
        return this.docility;
    }
    
    public void setDocility(String docility) {
        this.docility = docility;
    }
    public String getTenderness() {
        return this.tenderness;
    }
    
    public void setTenderness(String tenderness) {
        this.tenderness = tenderness;
    }
    public String getBreastFront() {
        return this.breastFront;
    }
    
    public void setBreastFront(String breastFront) {
        this.breastFront = breastFront;
    }
    public String getBreastBack() {
        return this.breastBack;
    }
    
    public void setBreastBack(String breastBack) {
        this.breastBack = breastBack;
    }
    public String getBreastBackHeight() {
        return this.breastBackHeight;
    }
    
    public void setBreastBackHeight(String breastBackHeight) {
        this.breastBackHeight = breastBackHeight;
    }
    public String getBreastBackWidth() {
        return this.breastBackWidth;
    }
    
    public void setBreastBackWidth(String breastBackWidth) {
        this.breastBackWidth = breastBackWidth;
    }
    public String getBreastDepth() {
        return this.breastDepth;
    }
    
    public void setBreastDepth(String breastDepth) {
        this.breastDepth = breastDepth;
    }
    public String getLenthNipple() {
        return this.lenthNipple;
    }
    
    public void setLenthNipple(String lenthNipple) {
        this.lenthNipple = lenthNipple;
    }
    public String getFrontBreast() {
        return this.frontBreast;
    }
    
    public void setFrontBreast(String frontBreast) {
        this.frontBreast = frontBreast;
    }
    public String getBackBreast() {
        return this.backBreast;
    }
    
    public void setBackBreast(String backBreast) {
        this.backBreast = backBreast;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public String getBodyDepth() {
        return this.bodyDepth;
    }
    
    public void setBodyDepth(String bodyDepth) {
        this.bodyDepth = bodyDepth;
    }
    public String getStong() {
        return this.stong;
    }
    
    public void setStong(String stong) {
        this.stong = stong;
    }
    public String getHipAngle() {
        return this.hipAngle;
    }
    
    public void setHipAngle(String hipAngle) {
        this.hipAngle = hipAngle;
    }
    public String getWidthHips() {
        return this.widthHips;
    }
    
    public void setWidthHips(String widthHips) {
        this.widthHips = widthHips;
    }
    public String getCurBackLegs() {
        return this.curBackLegs;
    }
    
    public void setCurBackLegs(String curBackLegs) {
        this.curBackLegs = curBackLegs;
    }
    public String getStraightBackLegs() {
        return this.straightBackLegs;
    }
    
    public void setStraightBackLegs(String straightBackLegs) {
        this.straightBackLegs = straightBackLegs;
    }
    public String getHoofCorner() {
        return this.hoofCorner;
    }
    
    public void setHoofCorner(String hoofCorner) {
        this.hoofCorner = hoofCorner;
    }
    public String getPointLegHoof() {
        return this.pointLegHoof;
    }
    
    public void setPointLegHoof(String pointLegHoof) {
        this.pointLegHoof = pointLegHoof;
    }
    public String getAgeYield() {
        return this.ageYield;
    }
    
    public void setAgeYield(String ageYield) {
        this.ageYield = ageYield;
    }
    public String getMilk() {
        return this.milk;
    }
    
    public void setMilk(String milk) {
        this.milk = milk;
    }
    public String getProtein() {
        return this.protein;
    }
    
    public void setProtein(String protein) {
        this.protein = protein;
    }
    public String getFat() {
        return this.fat;
    }
    
    public void setFat(String fat) {
        this.fat = fat;
    }
    public String getNetIncome() {
        return this.netIncome;
    }
    
    public void setNetIncome(String netIncome) {
        this.netIncome = netIncome;
    }
    public String getBirthRate() {
        return this.birthRate;
    }
    
    public void setBirthRate(String birthRate) {
        this.birthRate = birthRate;
    }
    public String getDaughterBirthRate() {
        return this.daughterBirthRate;
    }
    
    public void setDaughterBirthRate(String daughterBirthRate) {
        this.daughterBirthRate = daughterBirthRate;
    }
    public String getFirstDeath() {
        return this.firstDeath;
    }
    
    public void setFirstDeath(String firstDeath) {
        this.firstDeath = firstDeath;
    }
    public String getDaughterFirstDeath() {
        return this.daughterFirstDeath;
    }
    
    public void setDaughterFirstDeath(String daughterFirstDeath) {
        this.daughterFirstDeath = daughterFirstDeath;
    }
    public String getDaughterPregnancyRate() {
        return this.daughterPregnancyRate;
    }
    
    public void setDaughterPregnancyRate(String daughterPregnancyRate) {
        this.daughterPregnancyRate = daughterPregnancyRate;
    }
    public String getSomatic() {
        return this.somatic;
    }
    
    public void setSomatic(String somatic) {
        this.somatic = somatic;
    }
    public String getTm() {
        return this.tm;
    }
    
    public void setTm(String tm) {
        this.tm = tm;
    }
    public String getSc() {
        return this.sc;
    }
    
    public void setSc(String sc) {
        this.sc = sc;
    }
    public String getRea() {
        return this.rea;
    }
    
    public void setRea(String rea) {
        this.rea = rea;
    }
    public String getImf() {
        return this.imf;
    }
    
    public void setImf(String imf) {
        this.imf = imf;
    }
    public String getRump() {
        return this.rump;
    }
    
    public void setRump(String rump) {
        this.rump = rump;
    }
    public String getAdg() {
        return this.adg;
    }
    
    public void setAdg(String adg) {
        this.adg = adg;
    }
    public String getCalvingEaseDir() {
        return this.calvingEaseDir;
    }
    
    public void setCalvingEaseDir(String calvingEaseDir) {
        this.calvingEaseDir = calvingEaseDir;
    }
    public String getCalvingEaseDtrs() {
        return this.calvingEaseDtrs;
    }
    
    public void setCalvingEaseDtrs(String calvingEaseDtrs) {
        this.calvingEaseDtrs = calvingEaseDtrs;
    }
    public String getGestationLength() {
        return this.gestationLength;
    }
    
    public void setGestationLength(String gestationLength) {
        this.gestationLength = gestationLength;
    }
    public String get200dayWt() {
        return this.200dayWt;
    }
    
    public void set200dayWt(String 200dayWt) {
        this.200dayWt = 200dayWt;
    }
    public String get400dayWt() {
        return this.400dayWt;
    }
    
    public void set400dayWt(String 400dayWt) {
        this.400dayWt = 400dayWt;
    }
    public String get600dayWt() {
        return this.600dayWt;
    }
    
    public void set600dayWt(String 600dayWt) {
        this.600dayWt = 600dayWt;
    }
    public String getMatCow() {
        return this.matCow;
    }
    
    public void setMatCow(String matCow) {
        this.matCow = matCow;
    }
    public String get200dayMilk() {
        return this.200dayMilk;
    }
    
    public void set200dayMilk(String 200dayMilk) {
        this.200dayMilk = 200dayMilk;
    }
    public String getScrotalSize() {
        return this.scrotalSize;
    }
    
    public void setScrotalSize(String scrotalSize) {
        this.scrotalSize = scrotalSize;
    }
    public String getCarcaseWt() {
        return this.carcaseWt;
    }
    
    public void setCarcaseWt(String carcaseWt) {
        this.carcaseWt = carcaseWt;
    }
    public String getEyeMuscleArea() {
        return this.eyeMuscleArea;
    }
    
    public void setEyeMuscleArea(String eyeMuscleArea) {
        this.eyeMuscleArea = eyeMuscleArea;
    }
    public String getRibFat() {
        return this.ribFat;
    }
    
    public void setRibFat(String ribFat) {
        this.ribFat = ribFat;
    }
    public String getRetailBeefYield() {
        return this.retailBeefYield;
    }
    
    public void setRetailBeefYield(String retailBeefYield) {
        this.retailBeefYield = retailBeefYield;
    }
    public String getEbv() {
        return this.ebv;
    }
    
    public void setEbv(String ebv) {
        this.ebv = ebv;
    }
    public String getAcc() {
        return this.acc;
    }
    
    public void setAcc(String acc) {
        this.acc = acc;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getPriceStart() {
        return this.priceStart;
    }
    
    public void setPriceStart(String priceStart) {
        this.priceStart = priceStart;
    }
    public String getPriceEnd() {
        return this.priceEnd;
    }
    
    public void setPriceEnd(String priceEnd) {
        this.priceEnd = priceEnd;
    }
    public String getDateReport() {
        return this.dateReport;
    }
    
    public void setDateReport(String dateReport) {
        this.dateReport = dateReport;
    }
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    public String getNumberEar() {
        return this.numberEar;
    }
    
    public void setNumberEar(String numberEar) {
        this.numberEar = numberEar;
    }
    public Set getCattles() {
        return this.cattles;
    }
    
    public void setCattles(Set cattles) {
        this.cattles = cattles;
    }




}


