// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * CattleWean generated by hbm2java
 */
public class CattleWean  implements java.io.Serializable {


     private Integer id;
     private Cattle cattle;
     private Member member;
     private Date date;
     private String weigthwean;
     private String note;
     private String performer;

    public CattleWean() {
    }

    public CattleWean(Cattle cattle, Member member, Date date, String weigthwean, String note, String performer) {
       this.cattle = cattle;
       this.member = member;
       this.date = date;
       this.weigthwean = weigthwean;
       this.note = note;
       this.performer = performer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cattle getCattle() {
        return this.cattle;
    }
    
    public void setCattle(Cattle cattle) {
        this.cattle = cattle;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getWeigthwean() {
        return this.weigthwean;
    }
    
    public void setWeigthwean(String weigthwean) {
        this.weigthwean = weigthwean;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getPerformer() {
        return this.performer;
    }
    
    public void setPerformer(String performer) {
        this.performer = performer;
    }




}


