// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * CattleShow generated by hbm2java
 */
public class CattleShow  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private String name;
     private Date birthday;
     private String sex;
     private String gene;
     private int cattleStatus;
     private String commen;
     private String father;
     private String mother;
     private String deverloper;
     private String pic;
     private String pedegree;

    public CattleShow() {
    }

	
    public CattleShow(Member member, int cattleStatus) {
        this.member = member;
        this.cattleStatus = cattleStatus;
    }
    public CattleShow(Member member, String name, Date birthday, String sex, String gene, int cattleStatus, String commen, String father, String mother, String deverloper, String pic, String pedegree) {
       this.member = member;
       this.name = name;
       this.birthday = birthday;
       this.sex = sex;
       this.gene = gene;
       this.cattleStatus = cattleStatus;
       this.commen = commen;
       this.father = father;
       this.mother = mother;
       this.deverloper = deverloper;
       this.pic = pic;
       this.pedegree = pedegree;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getGene() {
        return this.gene;
    }
    
    public void setGene(String gene) {
        this.gene = gene;
    }
    public int getCattleStatus() {
        return this.cattleStatus;
    }
    
    public void setCattleStatus(int cattleStatus) {
        this.cattleStatus = cattleStatus;
    }
    public String getCommen() {
        return this.commen;
    }
    
    public void setCommen(String commen) {
        this.commen = commen;
    }
    public String getFather() {
        return this.father;
    }
    
    public void setFather(String father) {
        this.father = father;
    }
    public String getMother() {
        return this.mother;
    }
    
    public void setMother(String mother) {
        this.mother = mother;
    }
    public String getDeverloper() {
        return this.deverloper;
    }
    
    public void setDeverloper(String deverloper) {
        this.deverloper = deverloper;
    }
    public String getPic() {
        return this.pic;
    }
    
    public void setPic(String pic) {
        this.pic = pic;
    }
    public String getPedegree() {
        return this.pedegree;
    }
    
    public void setPedegree(String pedegree) {
        this.pedegree = pedegree;
    }




}


