// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * CattleStamp generated by hbm2java
 */
public class CattleStamp  implements java.io.Serializable {


     private Integer id;
     private Cattle cattle;
     private Member member;
     private String stampNumber;
     private String shortCountry;
     private String numberCountry;
     private String shortInternational;
     private String numberInternational;
     private Date date;
     private String performer;
     private String note;

    public CattleStamp() {
    }

    public CattleStamp(Cattle cattle, Member member, String stampNumber, String shortCountry, String numberCountry, String shortInternational, String numberInternational, Date date, String performer, String note) {
       this.cattle = cattle;
       this.member = member;
       this.stampNumber = stampNumber;
       this.shortCountry = shortCountry;
       this.numberCountry = numberCountry;
       this.shortInternational = shortInternational;
       this.numberInternational = numberInternational;
       this.date = date;
       this.performer = performer;
       this.note = note;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cattle getCattle() {
        return this.cattle;
    }
    
    public void setCattle(Cattle cattle) {
        this.cattle = cattle;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public String getStampNumber() {
        return this.stampNumber;
    }
    
    public void setStampNumber(String stampNumber) {
        this.stampNumber = stampNumber;
    }
    public String getShortCountry() {
        return this.shortCountry;
    }
    
    public void setShortCountry(String shortCountry) {
        this.shortCountry = shortCountry;
    }
    public String getNumberCountry() {
        return this.numberCountry;
    }
    
    public void setNumberCountry(String numberCountry) {
        this.numberCountry = numberCountry;
    }
    public String getShortInternational() {
        return this.shortInternational;
    }
    
    public void setShortInternational(String shortInternational) {
        this.shortInternational = shortInternational;
    }
    public String getNumberInternational() {
        return this.numberInternational;
    }
    
    public void setNumberInternational(String numberInternational) {
        this.numberInternational = numberInternational;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getPerformer() {
        return this.performer;
    }
    
    public void setPerformer(String performer) {
        this.performer = performer;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


