// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * CattleStrain generated by hbm2java
 */
public class CattleStrain  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private TypeCattle typeCattle;
     private TypeClassBeef typeClassBeef;
     private TypeClassDairy typeClassDairy;
     private String name;
     private String privateNo;
     private String sex;
     private Date birthday;
     private String color;
     private String pic;
     private String pedigree;
     private String lot;
     private String bidder;
     private Float weight;
     private Float weightBirth;
     private Float weightWean;
     private Float weightYear;
     private Float strainStartPrice;
     private Float strainEndPrice;
     private Float strainPercen;
     private Float strainExcise;
     private String father;
     private String mother;
     private String grandfather;
     private String grandmother;
     private String dadGrandfather;
     private String dadGrandmother;
     private String momGrandfather;
     private String momGrandmother;
     private String grandpa;
     private String gramdma;
     private String momGrandpa;
     private String momGrandma;
     private String dadGrandpa;
     private String dadGrandma;
     private String rateMilk;
     private String description;
     private Integer cattleStatus;
     private String commen;

    public CattleStrain() {
    }

	
    public CattleStrain(Member member) {
        this.member = member;
    }
    public CattleStrain(Member member, TypeCattle typeCattle, TypeClassBeef typeClassBeef, TypeClassDairy typeClassDairy, String name, String privateNo, String sex, Date birthday, String color, String pic, String pedigree, String lot, String bidder, Float weight, Float weightBirth, Float weightWean, Float weightYear, Float strainStartPrice, Float strainEndPrice, Float strainPercen, Float strainExcise, String father, String mother, String grandfather, String grandmother, String dadGrandfather, String dadGrandmother, String momGrandfather, String momGrandmother, String grandpa, String gramdma, String momGrandpa, String momGrandma, String dadGrandpa, String dadGrandma, String rateMilk, String description, Integer cattleStatus, String commen) {
       this.member = member;
       this.typeCattle = typeCattle;
       this.typeClassBeef = typeClassBeef;
       this.typeClassDairy = typeClassDairy;
       this.name = name;
       this.privateNo = privateNo;
       this.sex = sex;
       this.birthday = birthday;
       this.color = color;
       this.pic = pic;
       this.pedigree = pedigree;
       this.lot = lot;
       this.bidder = bidder;
       this.weight = weight;
       this.weightBirth = weightBirth;
       this.weightWean = weightWean;
       this.weightYear = weightYear;
       this.strainStartPrice = strainStartPrice;
       this.strainEndPrice = strainEndPrice;
       this.strainPercen = strainPercen;
       this.strainExcise = strainExcise;
       this.father = father;
       this.mother = mother;
       this.grandfather = grandfather;
       this.grandmother = grandmother;
       this.dadGrandfather = dadGrandfather;
       this.dadGrandmother = dadGrandmother;
       this.momGrandfather = momGrandfather;
       this.momGrandmother = momGrandmother;
       this.grandpa = grandpa;
       this.gramdma = gramdma;
       this.momGrandpa = momGrandpa;
       this.momGrandma = momGrandma;
       this.dadGrandpa = dadGrandpa;
       this.dadGrandma = dadGrandma;
       this.rateMilk = rateMilk;
       this.description = description;
       this.cattleStatus = cattleStatus;
       this.commen = commen;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public TypeCattle getTypeCattle() {
        return this.typeCattle;
    }
    
    public void setTypeCattle(TypeCattle typeCattle) {
        this.typeCattle = typeCattle;
    }
    public TypeClassBeef getTypeClassBeef() {
        return this.typeClassBeef;
    }
    
    public void setTypeClassBeef(TypeClassBeef typeClassBeef) {
        this.typeClassBeef = typeClassBeef;
    }
    public TypeClassDairy getTypeClassDairy() {
        return this.typeClassDairy;
    }
    
    public void setTypeClassDairy(TypeClassDairy typeClassDairy) {
        this.typeClassDairy = typeClassDairy;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPrivateNo() {
        return this.privateNo;
    }
    
    public void setPrivateNo(String privateNo) {
        this.privateNo = privateNo;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getPic() {
        return this.pic;
    }
    
    public void setPic(String pic) {
        this.pic = pic;
    }
    public String getPedigree() {
        return this.pedigree;
    }
    
    public void setPedigree(String pedigree) {
        this.pedigree = pedigree;
    }
    public String getLot() {
        return this.lot;
    }
    
    public void setLot(String lot) {
        this.lot = lot;
    }
    public String getBidder() {
        return this.bidder;
    }
    
    public void setBidder(String bidder) {
        this.bidder = bidder;
    }
    public Float getWeight() {
        return this.weight;
    }
    
    public void setWeight(Float weight) {
        this.weight = weight;
    }
    public Float getWeightBirth() {
        return this.weightBirth;
    }
    
    public void setWeightBirth(Float weightBirth) {
        this.weightBirth = weightBirth;
    }
    public Float getWeightWean() {
        return this.weightWean;
    }
    
    public void setWeightWean(Float weightWean) {
        this.weightWean = weightWean;
    }
    public Float getWeightYear() {
        return this.weightYear;
    }
    
    public void setWeightYear(Float weightYear) {
        this.weightYear = weightYear;
    }
    public Float getStrainStartPrice() {
        return this.strainStartPrice;
    }
    
    public void setStrainStartPrice(Float strainStartPrice) {
        this.strainStartPrice = strainStartPrice;
    }
    public Float getStrainEndPrice() {
        return this.strainEndPrice;
    }
    
    public void setStrainEndPrice(Float strainEndPrice) {
        this.strainEndPrice = strainEndPrice;
    }
    public Float getStrainPercen() {
        return this.strainPercen;
    }
    
    public void setStrainPercen(Float strainPercen) {
        this.strainPercen = strainPercen;
    }
    public Float getStrainExcise() {
        return this.strainExcise;
    }
    
    public void setStrainExcise(Float strainExcise) {
        this.strainExcise = strainExcise;
    }
    public String getFather() {
        return this.father;
    }
    
    public void setFather(String father) {
        this.father = father;
    }
    public String getMother() {
        return this.mother;
    }
    
    public void setMother(String mother) {
        this.mother = mother;
    }
    public String getGrandfather() {
        return this.grandfather;
    }
    
    public void setGrandfather(String grandfather) {
        this.grandfather = grandfather;
    }
    public String getGrandmother() {
        return this.grandmother;
    }
    
    public void setGrandmother(String grandmother) {
        this.grandmother = grandmother;
    }
    public String getDadGrandfather() {
        return this.dadGrandfather;
    }
    
    public void setDadGrandfather(String dadGrandfather) {
        this.dadGrandfather = dadGrandfather;
    }
    public String getDadGrandmother() {
        return this.dadGrandmother;
    }
    
    public void setDadGrandmother(String dadGrandmother) {
        this.dadGrandmother = dadGrandmother;
    }
    public String getMomGrandfather() {
        return this.momGrandfather;
    }
    
    public void setMomGrandfather(String momGrandfather) {
        this.momGrandfather = momGrandfather;
    }
    public String getMomGrandmother() {
        return this.momGrandmother;
    }
    
    public void setMomGrandmother(String momGrandmother) {
        this.momGrandmother = momGrandmother;
    }
    public String getGrandpa() {
        return this.grandpa;
    }
    
    public void setGrandpa(String grandpa) {
        this.grandpa = grandpa;
    }
    public String getGramdma() {
        return this.gramdma;
    }
    
    public void setGramdma(String gramdma) {
        this.gramdma = gramdma;
    }
    public String getMomGrandpa() {
        return this.momGrandpa;
    }
    
    public void setMomGrandpa(String momGrandpa) {
        this.momGrandpa = momGrandpa;
    }
    public String getMomGrandma() {
        return this.momGrandma;
    }
    
    public void setMomGrandma(String momGrandma) {
        this.momGrandma = momGrandma;
    }
    public String getDadGrandpa() {
        return this.dadGrandpa;
    }
    
    public void setDadGrandpa(String dadGrandpa) {
        this.dadGrandpa = dadGrandpa;
    }
    public String getDadGrandma() {
        return this.dadGrandma;
    }
    
    public void setDadGrandma(String dadGrandma) {
        this.dadGrandma = dadGrandma;
    }
    public String getRateMilk() {
        return this.rateMilk;
    }
    
    public void setRateMilk(String rateMilk) {
        this.rateMilk = rateMilk;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getCattleStatus() {
        return this.cattleStatus;
    }
    
    public void setCattleStatus(Integer cattleStatus) {
        this.cattleStatus = cattleStatus;
    }
    public String getCommen() {
        return this.commen;
    }
    
    public void setCommen(String commen) {
        this.commen = commen;
    }




}


