package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CattleStamp generated by hbm2java
 */
@Entity
@Table(name = "cattle_stamp", catalog = "induct")
public class CattleStamp implements java.io.Serializable {

	private Integer id;
	private Cattle cattle;
	private Member member;
	private String stampNumber;
	private String date;
	private String shortCountry;
	private String numberCountry;
	private String shortInternational;
	private String numberInternational;
	private String note;

	public CattleStamp() {
	}

	public CattleStamp(Cattle cattle, Member member, String stampNumber, String date, String shortCountry,
			String numberCountry, String shortInternational, String numberInternational, String note) {
		this.cattle = cattle;
		this.member = member;
		this.stampNumber = stampNumber;
		this.date = date;
		this.shortCountry = shortCountry;
		this.numberCountry = numberCountry;
		this.shortInternational = shortInternational;
		this.numberInternational = numberInternational;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cattle_id")
	public Cattle getCattle() {
		return this.cattle;
	}

	public void setCattle(Cattle cattle) {
		this.cattle = cattle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "stamp_number", length = 45)
	public String getStampNumber() {
		return this.stampNumber;
	}

	public void setStampNumber(String stampNumber) {
		this.stampNumber = stampNumber;
	}

	@Column(name = "date", length = 10)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "short_country", length = 45)
	public String getShortCountry() {
		return this.shortCountry;
	}

	public void setShortCountry(String shortCountry) {
		this.shortCountry = shortCountry;
	}

	@Column(name = "number_country", length = 45)
	public String getNumberCountry() {
		return this.numberCountry;
	}

	public void setNumberCountry(String numberCountry) {
		this.numberCountry = numberCountry;
	}

	@Column(name = "short_international", length = 45)
	public String getShortInternational() {
		return this.shortInternational;
	}

	public void setShortInternational(String shortInternational) {
		this.shortInternational = shortInternational;
	}

	@Column(name = "number_international", length = 45)
	public String getNumberInternational() {
		return this.numberInternational;
	}

	public void setNumberInternational(String numberInternational) {
		this.numberInternational = numberInternational;
	}

	@Column(name = "note", length = 45)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
