// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * CattleFatten generated by hbm2java
 */
public class CattleFatten  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private Integer quantity;
     private String lot;
     private String gene;
     private Float weight;
     private Float startPrice;
     private Float endPrice;
     private Float totalPercen;
     private Float totalExcise;
     private int cattleStatus;
     private String commen;
     private String pic;
     private String bidder;
     private Set fattenLists = new HashSet(0);

    public CattleFatten() {
    }

	
    public CattleFatten(Member member, String gene, int cattleStatus) {
        this.member = member;
        this.gene = gene;
        this.cattleStatus = cattleStatus;
    }
    public CattleFatten(Member member, Integer quantity, String lot, String gene, Float weight, Float startPrice, Float endPrice, Float totalPercen, Float totalExcise, int cattleStatus, String commen, String pic, String bidder, Set fattenLists) {
       this.member = member;
       this.quantity = quantity;
       this.lot = lot;
       this.gene = gene;
       this.weight = weight;
       this.startPrice = startPrice;
       this.endPrice = endPrice;
       this.totalPercen = totalPercen;
       this.totalExcise = totalExcise;
       this.cattleStatus = cattleStatus;
       this.commen = commen;
       this.pic = pic;
       this.bidder = bidder;
       this.fattenLists = fattenLists;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public String getLot() {
        return this.lot;
    }
    
    public void setLot(String lot) {
        this.lot = lot;
    }
    public String getGene() {
        return this.gene;
    }
    
    public void setGene(String gene) {
        this.gene = gene;
    }
    public Float getWeight() {
        return this.weight;
    }
    
    public void setWeight(Float weight) {
        this.weight = weight;
    }
    public Float getStartPrice() {
        return this.startPrice;
    }
    
    public void setStartPrice(Float startPrice) {
        this.startPrice = startPrice;
    }
    public Float getEndPrice() {
        return this.endPrice;
    }
    
    public void setEndPrice(Float endPrice) {
        this.endPrice = endPrice;
    }
    public Float getTotalPercen() {
        return this.totalPercen;
    }
    
    public void setTotalPercen(Float totalPercen) {
        this.totalPercen = totalPercen;
    }
    public Float getTotalExcise() {
        return this.totalExcise;
    }
    
    public void setTotalExcise(Float totalExcise) {
        this.totalExcise = totalExcise;
    }
    public int getCattleStatus() {
        return this.cattleStatus;
    }
    
    public void setCattleStatus(int cattleStatus) {
        this.cattleStatus = cattleStatus;
    }
    public String getCommen() {
        return this.commen;
    }
    
    public void setCommen(String commen) {
        this.commen = commen;
    }
    public String getPic() {
        return this.pic;
    }
    
    public void setPic(String pic) {
        this.pic = pic;
    }
    public String getBidder() {
        return this.bidder;
    }
    
    public void setBidder(String bidder) {
        this.bidder = bidder;
    }
    public Set getFattenLists() {
        return this.fattenLists;
    }
    
    public void setFattenLists(Set fattenLists) {
        this.fattenLists = fattenLists;
    }




}


