// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Color generated by hbm2java
 */
public class Color  implements java.io.Serializable {


     private Integer id;
     private String value;
     private Set cattles = new HashSet(0);
     private Set semens = new HashSet(0);

    public Color() {
    }

	
    public Color(String value) {
        this.value = value;
    }
    public Color(String value, Set cattles, Set semens) {
       this.value = value;
       this.cattles = cattles;
       this.semens = semens;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set getCattles() {
        return this.cattles;
    }
    
    public void setCattles(Set cattles) {
        this.cattles = cattles;
    }
    public Set getSemens() {
        return this.semens;
    }
    
    public void setSemens(Set semens) {
        this.semens = semens;
    }




}


