package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Color generated by hbm2java
 */
@Entity
@Table(name = "color", catalog = "induct")
public class Color implements java.io.Serializable {

	private Integer id;
	private String nameColor;
	private Set<Cattle> cattles = new HashSet<Cattle>(0);

	public Color() {
	}

	public Color(String nameColor, Set<Cattle> cattles) {
		this.nameColor = nameColor;
		this.cattles = cattles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name_color", length = 45)
	public String getNameColor() {
		return this.nameColor;
	}

	public void setNameColor(String nameColor) {
		this.nameColor = nameColor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<Cattle> getCattles() {
		return this.cattles;
	}

	public void setCattles(Set<Cattle> cattles) {
		this.cattles = cattles;
	}

}
