package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CountBreed generated by hbm2java
 */
@Entity
@Table(name = "count_breed", catalog = "induct")
public class CountBreed implements java.io.Serializable {

	private Integer id;
	private Cattle cattle;
	private Integer count;
	private String year;
	private Set<Breeding> breedings = new HashSet<Breeding>(0);

	public CountBreed() {
	}

	public CountBreed(Cattle cattle, Integer count, String year, Set<Breeding> breedings) {
		this.cattle = cattle;
		this.count = count;
		this.year = year;
		this.breedings = breedings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cattle_id")
	public Cattle getCattle() {
		return this.cattle;
	}

	public void setCattle(Cattle cattle) {
		this.cattle = cattle;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "year", length = 45)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countBreed")
	public Set<Breeding> getBreedings() {
		return this.breedings;
	}

	public void setBreedings(Set<Breeding> breedings) {
		this.breedings = breedings;
	}

}
