// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * CountBreed generated by hbm2java
 */
public class CountBreed  implements java.io.Serializable {


     private Integer id;
     private Cattle cattle;
     private Integer count;
     private String year;
     private Set breedings = new HashSet(0);

    public CountBreed() {
    }

    public CountBreed(Cattle cattle, Integer count, String year, Set breedings) {
       this.cattle = cattle;
       this.count = count;
       this.year = year;
       this.breedings = breedings;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cattle getCattle() {
        return this.cattle;
    }
    
    public void setCattle(Cattle cattle) {
        this.cattle = cattle;
    }
    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }
    public Set getBreedings() {
        return this.breedings;
    }
    
    public void setBreedings(Set breedings) {
        this.breedings = breedings;
    }




}


