// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Disease generated by hbm2java
 */
public class Disease  implements java.io.Serializable {


     private Integer id;
     private CableDisease cableDisease;
     private Member member;
     private String nameDisease;
     private String symptomsOfDisease;
     private String causeOfTheDisease;
     private String complications;
     private String note;
     private String image;
     private Set treatmentHistories = new HashSet(0);

    public Disease() {
    }

    public Disease(CableDisease cableDisease, Member member, String nameDisease, String symptomsOfDisease, String causeOfTheDisease, String complications, String note, String image, Set treatmentHistories) {
       this.cableDisease = cableDisease;
       this.member = member;
       this.nameDisease = nameDisease;
       this.symptomsOfDisease = symptomsOfDisease;
       this.causeOfTheDisease = causeOfTheDisease;
       this.complications = complications;
       this.note = note;
       this.image = image;
       this.treatmentHistories = treatmentHistories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CableDisease getCableDisease() {
        return this.cableDisease;
    }
    
    public void setCableDisease(CableDisease cableDisease) {
        this.cableDisease = cableDisease;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public String getNameDisease() {
        return this.nameDisease;
    }
    
    public void setNameDisease(String nameDisease) {
        this.nameDisease = nameDisease;
    }
    public String getSymptomsOfDisease() {
        return this.symptomsOfDisease;
    }
    
    public void setSymptomsOfDisease(String symptomsOfDisease) {
        this.symptomsOfDisease = symptomsOfDisease;
    }
    public String getCauseOfTheDisease() {
        return this.causeOfTheDisease;
    }
    
    public void setCauseOfTheDisease(String causeOfTheDisease) {
        this.causeOfTheDisease = causeOfTheDisease;
    }
    public String getComplications() {
        return this.complications;
    }
    
    public void setComplications(String complications) {
        this.complications = complications;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set getTreatmentHistories() {
        return this.treatmentHistories;
    }
    
    public void setTreatmentHistories(Set treatmentHistories) {
        this.treatmentHistories = treatmentHistories;
    }




}


