package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.google.gson.annotations.Expose;

/**
 * Disease generated by hbm2java
 */
@Entity
@Table(name = "disease", catalog = "induct")
public class Disease implements java.io.Serializable {

	private Integer id;
	private Member member;
	private CableDisease cableDisease;
	@Expose private String nameDisease;
	@Expose private String symptomsOfDisease;
	@Expose private String causeOfTheDisease;
	private String complications;
	private String note;
	private String image;
	private Set<TreatmentHistory> treatmentHistories = new HashSet<TreatmentHistory>(0);

	public Disease() {
	}

	public Disease(Member member, CableDisease cableDisease, String nameDisease, String symptomsOfDisease,
			String causeOfTheDisease, String complications, String note, String image,
			Set<TreatmentHistory> treatmentHistories) {
		this.member = member;
		this.cableDisease = cableDisease;
		this.nameDisease = nameDisease;
		this.symptomsOfDisease = symptomsOfDisease;
		this.causeOfTheDisease = causeOfTheDisease;
		this.complications = complications;
		this.note = note;
		this.image = image;
		this.treatmentHistories = treatmentHistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cable_disease_id")
	public CableDisease getCableDisease() {
		return this.cableDisease;
	}

	public void setCableDisease(CableDisease cableDisease) {
		this.cableDisease = cableDisease;
	}

	@Column(name = "name_disease", length = 100)
	public String getNameDisease() {
		return this.nameDisease;
	}

	public void setNameDisease(String nameDisease) {
		this.nameDisease = nameDisease;
	}

	@Column(name = "symptoms_of_disease", length = 5000)
	public String getSymptomsOfDisease() {
		return this.symptomsOfDisease;
	}

	public void setSymptomsOfDisease(String symptomsOfDisease) {
		this.symptomsOfDisease = symptomsOfDisease;
	}

	@Column(name = "cause_of_the_disease", length = 4000)
	public String getCauseOfTheDisease() {
		return this.causeOfTheDisease;
	}

	public void setCauseOfTheDisease(String causeOfTheDisease) {
		this.causeOfTheDisease = causeOfTheDisease;
	}

	@Column(name = "complications", length = 4000)
	public String getComplications() {
		return this.complications;
	}

	public void setComplications(String complications) {
		this.complications = complications;
	}

	@Column(name = "note", length = 4000)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "image", length = 100)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "disease")
	public Set<TreatmentHistory> getTreatmentHistories() {
		return this.treatmentHistories;
	}

	public void setTreatmentHistories(Set<TreatmentHistory> treatmentHistories) {
		this.treatmentHistories = treatmentHistories;
	}

}
