// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * FattenList generated by hbm2java
 */
public class FattenList  implements java.io.Serializable {


     private Integer id;
     private CattleFatten cattleFatten;
     private String name;
     private Date birthday;
     private String farm;
     private String color;
     private String sex;
     private Float weight;

    public FattenList() {
    }

	
    public FattenList(CattleFatten cattleFatten) {
        this.cattleFatten = cattleFatten;
    }
    public FattenList(CattleFatten cattleFatten, String name, Date birthday, String farm, String color, String sex, Float weight) {
       this.cattleFatten = cattleFatten;
       this.name = name;
       this.birthday = birthday;
       this.farm = farm;
       this.color = color;
       this.sex = sex;
       this.weight = weight;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CattleFatten getCattleFatten() {
        return this.cattleFatten;
    }
    
    public void setCattleFatten(CattleFatten cattleFatten) {
        this.cattleFatten = cattleFatten;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getFarm() {
        return this.farm;
    }
    
    public void setFarm(String farm) {
        this.farm = farm;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public Float getWeight() {
        return this.weight;
    }
    
    public void setWeight(Float weight) {
        this.weight = weight;
    }




}


