// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Festivity generated by hbm2java
 */
public class Festivity  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private Type type;
     private String title;
     private String gene;
     private Date SWork;
     private Date EWork;
     private Date SData;
     private Date EData;
     private String logo;
     private String poster;
     private String details;
     private String location;
     private String referee;
     private Integer newStatus;
     private String cowId;
     private Integer percen;
     private String farmName;
     private String phone;
     private Set festivityFattenHistories = new HashSet(0);
     private Set worktogethers = new HashSet(0);
     private Set festivityShowHistories = new HashSet(0);
     private Set festivityStrainHistories = new HashSet(0);

    public Festivity() {
    }

    public Festivity(Member member, Type type, String title, String gene, Date SWork, Date EWork, Date SData, Date EData, String logo, String poster, String details, String location, String referee, Integer newStatus, String cowId, Integer percen, String farmName, String phone, Set festivityFattenHistories, Set worktogethers, Set festivityShowHistories, Set festivityStrainHistories) {
       this.member = member;
       this.type = type;
       this.title = title;
       this.gene = gene;
       this.SWork = SWork;
       this.EWork = EWork;
       this.SData = SData;
       this.EData = EData;
       this.logo = logo;
       this.poster = poster;
       this.details = details;
       this.location = location;
       this.referee = referee;
       this.newStatus = newStatus;
       this.cowId = cowId;
       this.percen = percen;
       this.farmName = farmName;
       this.phone = phone;
       this.festivityFattenHistories = festivityFattenHistories;
       this.worktogethers = worktogethers;
       this.festivityShowHistories = festivityShowHistories;
       this.festivityStrainHistories = festivityStrainHistories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getGene() {
        return this.gene;
    }
    
    public void setGene(String gene) {
        this.gene = gene;
    }
    public Date getSWork() {
        return this.SWork;
    }
    
    public void setSWork(Date SWork) {
        this.SWork = SWork;
    }
    public Date getEWork() {
        return this.EWork;
    }
    
    public void setEWork(Date EWork) {
        this.EWork = EWork;
    }
    public Date getSData() {
        return this.SData;
    }
    
    public void setSData(Date SData) {
        this.SData = SData;
    }
    public Date getEData() {
        return this.EData;
    }
    
    public void setEData(Date EData) {
        this.EData = EData;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public String getPoster() {
        return this.poster;
    }
    
    public void setPoster(String poster) {
        this.poster = poster;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getReferee() {
        return this.referee;
    }
    
    public void setReferee(String referee) {
        this.referee = referee;
    }
    public Integer getNewStatus() {
        return this.newStatus;
    }
    
    public void setNewStatus(Integer newStatus) {
        this.newStatus = newStatus;
    }
    public String getCowId() {
        return this.cowId;
    }
    
    public void setCowId(String cowId) {
        this.cowId = cowId;
    }
    public Integer getPercen() {
        return this.percen;
    }
    
    public void setPercen(Integer percen) {
        this.percen = percen;
    }
    public String getFarmName() {
        return this.farmName;
    }
    
    public void setFarmName(String farmName) {
        this.farmName = farmName;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Set getFestivityFattenHistories() {
        return this.festivityFattenHistories;
    }
    
    public void setFestivityFattenHistories(Set festivityFattenHistories) {
        this.festivityFattenHistories = festivityFattenHistories;
    }
    public Set getWorktogethers() {
        return this.worktogethers;
    }
    
    public void setWorktogethers(Set worktogethers) {
        this.worktogethers = worktogethers;
    }
    public Set getFestivityShowHistories() {
        return this.festivityShowHistories;
    }
    
    public void setFestivityShowHistories(Set festivityShowHistories) {
        this.festivityShowHistories = festivityShowHistories;
    }
    public Set getFestivityStrainHistories() {
        return this.festivityStrainHistories;
    }
    
    public void setFestivityStrainHistories(Set festivityStrainHistories) {
        this.festivityStrainHistories = festivityStrainHistories;
    }




}


