// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * FormulaRecord generated by hbm2java
 */
public class FormulaRecord  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private TypeFormula typeFormula;
     private String typecal;
     private String breed;
     private String weightperday;
     private String weight;
     private String age;
     private String pregnent;
     private String lactation;
     private String lactationperday;
     private String fatmilk;
     private String pricemilk;
     private String typeeating;
     private String strain;
     private String ndf;
     private String adf;
     private String tdn;
     private String nel;
     private String walk;
     private String needtdn;
     private String neednel;
     private String needadf;
     private String needndf;
     private String uip;
     private String dip;
     private String ca;
     private String p;
     private String vita;
     private Set typeNutrients = new HashSet(0);
     private Set cattleNutrients = new HashSet(0);
     private Set cattleDetails = new HashSet(0);
     private Set rawMaterialFormulas = new HashSet(0);

    public FormulaRecord() {
    }

    public FormulaRecord(Member member, TypeFormula typeFormula, String typecal, String breed, String weightperday, String weight, String age, String pregnent, String lactation, String lactationperday, String fatmilk, String pricemilk, String typeeating, String strain, String ndf, String adf, String tdn, String nel, String walk, String needtdn, String neednel, String needadf, String needndf, String uip, String dip, String ca, String p, String vita, Set typeNutrients, Set cattleNutrients, Set cattleDetails, Set rawMaterialFormulas) {
       this.member = member;
       this.typeFormula = typeFormula;
       this.typecal = typecal;
       this.breed = breed;
       this.weightperday = weightperday;
       this.weight = weight;
       this.age = age;
       this.pregnent = pregnent;
       this.lactation = lactation;
       this.lactationperday = lactationperday;
       this.fatmilk = fatmilk;
       this.pricemilk = pricemilk;
       this.typeeating = typeeating;
       this.strain = strain;
       this.ndf = ndf;
       this.adf = adf;
       this.tdn = tdn;
       this.nel = nel;
       this.walk = walk;
       this.needtdn = needtdn;
       this.neednel = neednel;
       this.needadf = needadf;
       this.needndf = needndf;
       this.uip = uip;
       this.dip = dip;
       this.ca = ca;
       this.p = p;
       this.vita = vita;
       this.typeNutrients = typeNutrients;
       this.cattleNutrients = cattleNutrients;
       this.cattleDetails = cattleDetails;
       this.rawMaterialFormulas = rawMaterialFormulas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public TypeFormula getTypeFormula() {
        return this.typeFormula;
    }
    
    public void setTypeFormula(TypeFormula typeFormula) {
        this.typeFormula = typeFormula;
    }
    public String getTypecal() {
        return this.typecal;
    }
    
    public void setTypecal(String typecal) {
        this.typecal = typecal;
    }
    public String getBreed() {
        return this.breed;
    }
    
    public void setBreed(String breed) {
        this.breed = breed;
    }
    public String getWeightperday() {
        return this.weightperday;
    }
    
    public void setWeightperday(String weightperday) {
        this.weightperday = weightperday;
    }
    public String getWeight() {
        return this.weight;
    }
    
    public void setWeight(String weight) {
        this.weight = weight;
    }
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }
    public String getPregnent() {
        return this.pregnent;
    }
    
    public void setPregnent(String pregnent) {
        this.pregnent = pregnent;
    }
    public String getLactation() {
        return this.lactation;
    }
    
    public void setLactation(String lactation) {
        this.lactation = lactation;
    }
    public String getLactationperday() {
        return this.lactationperday;
    }
    
    public void setLactationperday(String lactationperday) {
        this.lactationperday = lactationperday;
    }
    public String getFatmilk() {
        return this.fatmilk;
    }
    
    public void setFatmilk(String fatmilk) {
        this.fatmilk = fatmilk;
    }
    public String getPricemilk() {
        return this.pricemilk;
    }
    
    public void setPricemilk(String pricemilk) {
        this.pricemilk = pricemilk;
    }
    public String getTypeeating() {
        return this.typeeating;
    }
    
    public void setTypeeating(String typeeating) {
        this.typeeating = typeeating;
    }
    public String getStrain() {
        return this.strain;
    }
    
    public void setStrain(String strain) {
        this.strain = strain;
    }
    public String getNdf() {
        return this.ndf;
    }
    
    public void setNdf(String ndf) {
        this.ndf = ndf;
    }
    public String getAdf() {
        return this.adf;
    }
    
    public void setAdf(String adf) {
        this.adf = adf;
    }
    public String getTdn() {
        return this.tdn;
    }
    
    public void setTdn(String tdn) {
        this.tdn = tdn;
    }
    public String getNel() {
        return this.nel;
    }
    
    public void setNel(String nel) {
        this.nel = nel;
    }
    public String getWalk() {
        return this.walk;
    }
    
    public void setWalk(String walk) {
        this.walk = walk;
    }
    public String getNeedtdn() {
        return this.needtdn;
    }
    
    public void setNeedtdn(String needtdn) {
        this.needtdn = needtdn;
    }
    public String getNeednel() {
        return this.neednel;
    }
    
    public void setNeednel(String neednel) {
        this.neednel = neednel;
    }
    public String getNeedadf() {
        return this.needadf;
    }
    
    public void setNeedadf(String needadf) {
        this.needadf = needadf;
    }
    public String getNeedndf() {
        return this.needndf;
    }
    
    public void setNeedndf(String needndf) {
        this.needndf = needndf;
    }
    public String getUip() {
        return this.uip;
    }
    
    public void setUip(String uip) {
        this.uip = uip;
    }
    public String getDip() {
        return this.dip;
    }
    
    public void setDip(String dip) {
        this.dip = dip;
    }
    public String getCa() {
        return this.ca;
    }
    
    public void setCa(String ca) {
        this.ca = ca;
    }
    public String getP() {
        return this.p;
    }
    
    public void setP(String p) {
        this.p = p;
    }
    public String getVita() {
        return this.vita;
    }
    
    public void setVita(String vita) {
        this.vita = vita;
    }
    public Set getTypeNutrients() {
        return this.typeNutrients;
    }
    
    public void setTypeNutrients(Set typeNutrients) {
        this.typeNutrients = typeNutrients;
    }
    public Set getCattleNutrients() {
        return this.cattleNutrients;
    }
    
    public void setCattleNutrients(Set cattleNutrients) {
        this.cattleNutrients = cattleNutrients;
    }
    public Set getCattleDetails() {
        return this.cattleDetails;
    }
    
    public void setCattleDetails(Set cattleDetails) {
        this.cattleDetails = cattleDetails;
    }
    public Set getRawMaterialFormulas() {
        return this.rawMaterialFormulas;
    }
    
    public void setRawMaterialFormulas(Set rawMaterialFormulas) {
        this.rawMaterialFormulas = rawMaterialFormulas;
    }




}


