// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * FormulaRecord2 generated by hbm2java
 */
public class FormulaRecord2  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private TypeFormula typeFormula;
     private Float sumweight;
     private Float cost;
     private Float dm1;
     private Float dm2;
     private Float cp1;
     private Float cp2;
     private Float tdn1;
     private Float tdn2;
     private Float ndf1;
     private Float ndf2;
     private Float vita1;
     private Float vita2;
     private Float vite1;
     private Float vite2;
     private Set rawMaterialFormulas = new HashSet(0);

    public FormulaRecord2() {
    }

    public FormulaRecord2(Member member, TypeFormula typeFormula, Float sumweight, Float cost, Float dm1, Float dm2, Float cp1, Float cp2, Float tdn1, Float tdn2, Float ndf1, Float ndf2, Float vita1, Float vita2, Float vite1, Float vite2, Set rawMaterialFormulas) {
       this.member = member;
       this.typeFormula = typeFormula;
       this.sumweight = sumweight;
       this.cost = cost;
       this.dm1 = dm1;
       this.dm2 = dm2;
       this.cp1 = cp1;
       this.cp2 = cp2;
       this.tdn1 = tdn1;
       this.tdn2 = tdn2;
       this.ndf1 = ndf1;
       this.ndf2 = ndf2;
       this.vita1 = vita1;
       this.vita2 = vita2;
       this.vite1 = vite1;
       this.vite2 = vite2;
       this.rawMaterialFormulas = rawMaterialFormulas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public TypeFormula getTypeFormula() {
        return this.typeFormula;
    }
    
    public void setTypeFormula(TypeFormula typeFormula) {
        this.typeFormula = typeFormula;
    }
    public Float getSumweight() {
        return this.sumweight;
    }
    
    public void setSumweight(Float sumweight) {
        this.sumweight = sumweight;
    }
    public Float getCost() {
        return this.cost;
    }
    
    public void setCost(Float cost) {
        this.cost = cost;
    }
    public Float getDm1() {
        return this.dm1;
    }
    
    public void setDm1(Float dm1) {
        this.dm1 = dm1;
    }
    public Float getDm2() {
        return this.dm2;
    }
    
    public void setDm2(Float dm2) {
        this.dm2 = dm2;
    }
    public Float getCp1() {
        return this.cp1;
    }
    
    public void setCp1(Float cp1) {
        this.cp1 = cp1;
    }
    public Float getCp2() {
        return this.cp2;
    }
    
    public void setCp2(Float cp2) {
        this.cp2 = cp2;
    }
    public Float getTdn1() {
        return this.tdn1;
    }
    
    public void setTdn1(Float tdn1) {
        this.tdn1 = tdn1;
    }
    public Float getTdn2() {
        return this.tdn2;
    }
    
    public void setTdn2(Float tdn2) {
        this.tdn2 = tdn2;
    }
    public Float getNdf1() {
        return this.ndf1;
    }
    
    public void setNdf1(Float ndf1) {
        this.ndf1 = ndf1;
    }
    public Float getNdf2() {
        return this.ndf2;
    }
    
    public void setNdf2(Float ndf2) {
        this.ndf2 = ndf2;
    }
    public Float getVita1() {
        return this.vita1;
    }
    
    public void setVita1(Float vita1) {
        this.vita1 = vita1;
    }
    public Float getVita2() {
        return this.vita2;
    }
    
    public void setVita2(Float vita2) {
        this.vita2 = vita2;
    }
    public Float getVite1() {
        return this.vite1;
    }
    
    public void setVite1(Float vite1) {
        this.vite1 = vite1;
    }
    public Float getVite2() {
        return this.vite2;
    }
    
    public void setVite2(Float vite2) {
        this.vite2 = vite2;
    }
    public Set getRawMaterialFormulas() {
        return this.rawMaterialFormulas;
    }
    
    public void setRawMaterialFormulas(Set rawMaterialFormulas) {
        this.rawMaterialFormulas = rawMaterialFormulas;
    }




}


