// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * GroupMedicine generated by hbm2java
 */
public class GroupMedicine  implements java.io.Serializable {


     private Integer id;
     private String value;
     private Set medicines = new HashSet(0);

    public GroupMedicine() {
    }

    public GroupMedicine(String value, Set medicines) {
       this.value = value;
       this.medicines = medicines;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set getMedicines() {
        return this.medicines;
    }
    
    public void setMedicines(Set medicines) {
        this.medicines = medicines;
    }




}


