package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GroupCattle generated by hbm2java
 */
@Entity
@Table(name = "group_cattle", catalog = "induct")
public class GroupCattle implements java.io.Serializable {

	private Integer id;
	private String groupNameCattle;
	private Set<Cattle> cattles = new HashSet<Cattle>(0);

	public GroupCattle() {
	}

	public GroupCattle(String groupNameCattle, Set<Cattle> cattles) {
		this.groupNameCattle = groupNameCattle;
		this.cattles = cattles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "group_name_cattle", length = 45)
	public String getGroupNameCattle() {
		return this.groupNameCattle;
	}

	public void setGroupNameCattle(String groupNameCattle) {
		this.groupNameCattle = groupNameCattle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupCattle")
	public Set<Cattle> getCattles() {
		return this.cattles;
	}

	public void setCattles(Set<Cattle> cattles) {
		this.cattles = cattles;
	}

}
