package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.google.gson.annotations.Expose;

/**
 * HornDetering generated by hbm2java
 */
@Entity
@Table(name = "horn_detering", catalog = "induct")
public class HornDetering implements java.io.Serializable {

	private Integer id;
	private Cattle cattle;
	private Member member;
	private TypeHorn typeHorn;
	private String date;
	private String note;

	public HornDetering() {
	}

	public HornDetering(Cattle cattle, Member member, TypeHorn typeHorn, String date, String note) {
		this.cattle = cattle;
		this.member = member;
		this.typeHorn = typeHorn;
		this.date = date;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cattle_id")
	public Cattle getCattle() {
		return this.cattle;
	}

	public void setCattle(Cattle cattle) {
		this.cattle = cattle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_horn_id")
	public TypeHorn getTypeHorn() {
		return this.typeHorn;
	}

	public void setTypeHorn(TypeHorn typeHorn) {
		this.typeHorn = typeHorn;
	}


	@Column(name = "date", length = 10)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "note", length = 450)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
