// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * HornDetering generated by hbm2java
 */
public class HornDetering  implements java.io.Serializable {


     private Integer id;
     private Cattle cattle;
     private Member member;
     private TypeHorn typeHorn;
     private Date date;
     private String note;
     private String performer;

    public HornDetering() {
    }

    public HornDetering(Cattle cattle, Member member, TypeHorn typeHorn, Date date, String note, String performer) {
       this.cattle = cattle;
       this.member = member;
       this.typeHorn = typeHorn;
       this.date = date;
       this.note = note;
       this.performer = performer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cattle getCattle() {
        return this.cattle;
    }
    
    public void setCattle(Cattle cattle) {
        this.cattle = cattle;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public TypeHorn getTypeHorn() {
        return this.typeHorn;
    }
    
    public void setTypeHorn(TypeHorn typeHorn) {
        this.typeHorn = typeHorn;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getPerformer() {
        return this.performer;
    }
    
    public void setPerformer(String performer) {
        this.performer = performer;
    }




}


