// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * MedicineRelease generated by hbm2java
 */
public class MedicineRelease  implements java.io.Serializable {


     private Integer id;
     private Medicine medicine;
     private Member member;
     private Date day;
     private Integer quantity;
     private Integer billId;

    public MedicineRelease() {
    }

	
    public MedicineRelease(Medicine medicine) {
        this.medicine = medicine;
    }
    public MedicineRelease(Medicine medicine, Member member, Date day, Integer quantity, Integer billId) {
       this.medicine = medicine;
       this.member = member;
       this.day = day;
       this.quantity = quantity;
       this.billId = billId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Medicine getMedicine() {
        return this.medicine;
    }
    
    public void setMedicine(Medicine medicine) {
        this.medicine = medicine;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Integer getBillId() {
        return this.billId;
    }
    
    public void setBillId(Integer billId) {
        this.billId = billId;
    }




}


