package healthcares.spring.model;
// Generated Sep 18, 2016 10:00:53 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MedicineImport generated by hbm2java
 */
@Entity
@Table(name = "medicine_import")
public class MedicineImport implements java.io.Serializable {

	private Integer id;
	private Medicine medicine;
	private Member member;
	private Integer lot;
	private Integer quantity;
	private Long price;
	private String import_;
	private String place;
	private String dayMfd;
	private String dayExp;
	private Integer billId;
	private int beforeQuantity;
	private String day;
	private int status;

	public MedicineImport() {
	}

	public MedicineImport(Medicine medicine, Member member, int beforeQuantity, String day, int status) {
		this.medicine = medicine;
		this.member = member;
		this.beforeQuantity = beforeQuantity;
		this.day = day;
		this.status = status;
	}

	public MedicineImport(Medicine medicine, Member member, Integer lot, Integer quantity, Long price, String import_,
			String place, String dayMfd, String dayExp, Integer billId, int beforeQuantity, String day, int status) {
		this.medicine = medicine;
		this.member = member;
		this.lot = lot;
		this.quantity = quantity;
		this.price = price;
		this.import_ = import_;
		this.place = place;
		this.dayMfd = dayMfd;
		this.dayExp = dayExp;
		this.billId = billId;
		this.beforeQuantity = beforeQuantity;
		this.day = day;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "medicine_id", nullable = false)
	public Medicine getMedicine() {
		return this.medicine;
	}

	public void setMedicine(Medicine medicine) {
		this.medicine = medicine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id", nullable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "lot")
	public Integer getLot() {
		return this.lot;
	}

	public void setLot(Integer lot) {
		this.lot = lot;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", precision = 10, scale = 0)
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	@Column(name = "import", length = 200)
	public String getImport_() {
		return this.import_;
	}

	public void setImport_(String import_) {
		this.import_ = import_;
	}

	@Column(name = "place", length = 100)
	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	@Column(name = "day_mfd", length = 10)
	public String getDayMfd() {
		return this.dayMfd;
	}

	public void setDayMfd(String dayMfd) {
		this.dayMfd = dayMfd;
	}

	@Column(name = "day_exp", length = 10)
	public String getDayExp() {
		return this.dayExp;
	}

	public void setDayExp(String dayExp) {
		this.dayExp = dayExp;
	}

	@Column(name = "bill_id")
	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	@Column(name = "before_quantity", nullable = false)
	public int getBeforeQuantity() {
		return this.beforeQuantity;
	}

	public void setBeforeQuantity(int beforeQuantity) {
		this.beforeQuantity = beforeQuantity;
	}
	
	@Column(name = "day", nullable = false, length = 10)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
