// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * MedicineOrder generated by hbm2java
 */
public class MedicineOrder  implements java.io.Serializable {


     private Integer id;
     private Medicine medicine;
     private Member member;
     private Integer quantity;
     private String note;
     private Integer billId;
     private Date day;

    public MedicineOrder() {
    }

	
    public MedicineOrder(Medicine medicine, Member member, Date day) {
        this.medicine = medicine;
        this.member = member;
        this.day = day;
    }
    public MedicineOrder(Medicine medicine, Member member, Integer quantity, String note, Integer billId, Date day) {
       this.medicine = medicine;
       this.member = member;
       this.quantity = quantity;
       this.note = note;
       this.billId = billId;
       this.day = day;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Medicine getMedicine() {
        return this.medicine;
    }
    
    public void setMedicine(Medicine medicine) {
        this.medicine = medicine;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Integer getBillId() {
        return this.billId;
    }
    
    public void setBillId(Integer billId) {
        this.billId = billId;
    }
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }




}


