// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medicine generated by hbm2java
 */
public class Medicine  implements java.io.Serializable {


     private Integer id;
     private GroupMedicine groupMedicine;
     private UnitMedicine unitMedicine;
     private String tradeName;
     private String scientificName;
     private String commonName;
     private Long qty;
     private Integer quantity;
     private String ingredient;
     private String properties;
     private String instruction;
     private String direction;
     private String contraindicated;
     private String caution;
     private String sideEffect;
     private String distanceDiscontinued;
     private Date mfgDate;
     private Date expDate;
     private String productBy;
     private String note;
     private String image;
     private String barcode;
     private String place;
     private int statusalert;
     private Integer medicineSuccess;
     private Integer medicineLost;
     private Set medicineReleases = new HashSet(0);
     private Set medicineOrders = new HashSet(0);
     private Set medicineImports = new HashSet(0);
     private Set treatmentHistories = new HashSet(0);

    public Medicine() {
    }

	
    public Medicine(int statusalert) {
        this.statusalert = statusalert;
    }
    public Medicine(GroupMedicine groupMedicine, UnitMedicine unitMedicine, String tradeName, String scientificName, String commonName, Long qty, Integer quantity, String ingredient, String properties, String instruction, String direction, String contraindicated, String caution, String sideEffect, String distanceDiscontinued, Date mfgDate, Date expDate, String productBy, String note, String image, String barcode, String place, int statusalert, Integer medicineSuccess, Integer medicineLost, Set medicineReleases, Set medicineOrders, Set medicineImports, Set treatmentHistories) {
       this.groupMedicine = groupMedicine;
       this.unitMedicine = unitMedicine;
       this.tradeName = tradeName;
       this.scientificName = scientificName;
       this.commonName = commonName;
       this.qty = qty;
       this.quantity = quantity;
       this.ingredient = ingredient;
       this.properties = properties;
       this.instruction = instruction;
       this.direction = direction;
       this.contraindicated = contraindicated;
       this.caution = caution;
       this.sideEffect = sideEffect;
       this.distanceDiscontinued = distanceDiscontinued;
       this.mfgDate = mfgDate;
       this.expDate = expDate;
       this.productBy = productBy;
       this.note = note;
       this.image = image;
       this.barcode = barcode;
       this.place = place;
       this.statusalert = statusalert;
       this.medicineSuccess = medicineSuccess;
       this.medicineLost = medicineLost;
       this.medicineReleases = medicineReleases;
       this.medicineOrders = medicineOrders;
       this.medicineImports = medicineImports;
       this.treatmentHistories = treatmentHistories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GroupMedicine getGroupMedicine() {
        return this.groupMedicine;
    }
    
    public void setGroupMedicine(GroupMedicine groupMedicine) {
        this.groupMedicine = groupMedicine;
    }
    public UnitMedicine getUnitMedicine() {
        return this.unitMedicine;
    }
    
    public void setUnitMedicine(UnitMedicine unitMedicine) {
        this.unitMedicine = unitMedicine;
    }
    public String getTradeName() {
        return this.tradeName;
    }
    
    public void setTradeName(String tradeName) {
        this.tradeName = tradeName;
    }
    public String getScientificName() {
        return this.scientificName;
    }
    
    public void setScientificName(String scientificName) {
        this.scientificName = scientificName;
    }
    public String getCommonName() {
        return this.commonName;
    }
    
    public void setCommonName(String commonName) {
        this.commonName = commonName;
    }
    public Long getQty() {
        return this.qty;
    }
    
    public void setQty(Long qty) {
        this.qty = qty;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public String getIngredient() {
        return this.ingredient;
    }
    
    public void setIngredient(String ingredient) {
        this.ingredient = ingredient;
    }
    public String getProperties() {
        return this.properties;
    }
    
    public void setProperties(String properties) {
        this.properties = properties;
    }
    public String getInstruction() {
        return this.instruction;
    }
    
    public void setInstruction(String instruction) {
        this.instruction = instruction;
    }
    public String getDirection() {
        return this.direction;
    }
    
    public void setDirection(String direction) {
        this.direction = direction;
    }
    public String getContraindicated() {
        return this.contraindicated;
    }
    
    public void setContraindicated(String contraindicated) {
        this.contraindicated = contraindicated;
    }
    public String getCaution() {
        return this.caution;
    }
    
    public void setCaution(String caution) {
        this.caution = caution;
    }
    public String getSideEffect() {
        return this.sideEffect;
    }
    
    public void setSideEffect(String sideEffect) {
        this.sideEffect = sideEffect;
    }
    public String getDistanceDiscontinued() {
        return this.distanceDiscontinued;
    }
    
    public void setDistanceDiscontinued(String distanceDiscontinued) {
        this.distanceDiscontinued = distanceDiscontinued;
    }
    public Date getMfgDate() {
        return this.mfgDate;
    }
    
    public void setMfgDate(Date mfgDate) {
        this.mfgDate = mfgDate;
    }
    public Date getExpDate() {
        return this.expDate;
    }
    
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }
    public String getProductBy() {
        return this.productBy;
    }
    
    public void setProductBy(String productBy) {
        this.productBy = productBy;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    public int getStatusalert() {
        return this.statusalert;
    }
    
    public void setStatusalert(int statusalert) {
        this.statusalert = statusalert;
    }
    public Integer getMedicineSuccess() {
        return this.medicineSuccess;
    }
    
    public void setMedicineSuccess(Integer medicineSuccess) {
        this.medicineSuccess = medicineSuccess;
    }
    public Integer getMedicineLost() {
        return this.medicineLost;
    }
    
    public void setMedicineLost(Integer medicineLost) {
        this.medicineLost = medicineLost;
    }
    public Set getMedicineReleases() {
        return this.medicineReleases;
    }
    
    public void setMedicineReleases(Set medicineReleases) {
        this.medicineReleases = medicineReleases;
    }
    public Set getMedicineOrders() {
        return this.medicineOrders;
    }
    
    public void setMedicineOrders(Set medicineOrders) {
        this.medicineOrders = medicineOrders;
    }
    public Set getMedicineImports() {
        return this.medicineImports;
    }
    
    public void setMedicineImports(Set medicineImports) {
        this.medicineImports = medicineImports;
    }
    public Set getTreatmentHistories() {
        return this.treatmentHistories;
    }
    
    public void setTreatmentHistories(Set treatmentHistories) {
        this.treatmentHistories = treatmentHistories;
    }




}


