package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.google.gson.annotations.Expose;

/**
 * Medicine generated by hbm2java
 */
@Entity
@Table(name = "medicine", catalog = "induct")
public class Medicine implements java.io.Serializable {

	private Integer id;
	private TypeMedicine typeMedicine;
	private UnitMedicine unitMedicine;
	private GroupMedicine groupMedicine;
	private String tradeName;
	@Expose private String scientificName;
	@Expose private String commonName;
	private Long qty;
	private Integer quantity;
	private String ingredient;
	@Expose private String properties;
	private String instruction;
	private String direction;
	private String contraindicated;
	private String caution;
	private String sideEffect;
	@Expose private String distanceDiscontinued;
	private String mfgDate;
	private String expDate;
	private String productBy;
	private String note;
	private String image;
	private String barcode;
	private Integer medicineSuccess;
	private Integer medicineLost;
	private Set<TreatmentHistory> treatmentHistories = new HashSet<TreatmentHistory>(0);

	public Medicine() {
	}

	public Medicine(TypeMedicine typeMedicine, UnitMedicine unitMedicine, GroupMedicine groupMedicine, String tradeName,
			String scientificName, String commonName, Long qty, Integer quantity, String ingredient, String properties,
			String instruction, String direction, String contraindicated, String caution, String sideEffect,
			String distanceDiscontinued, String mfgDate, String expDate, String productBy, String note, String image,
			String barcode, Integer medicineSuccess, Integer medicineLost, Set<TreatmentHistory> treatmentHistories) {
		this.typeMedicine = typeMedicine;
		this.unitMedicine = unitMedicine;
		this.groupMedicine = groupMedicine;
		this.tradeName = tradeName;
		this.scientificName = scientificName;
		this.commonName = commonName;
		this.qty = qty;
		this.quantity = quantity;
		this.ingredient = ingredient;
		this.properties = properties;
		this.instruction = instruction;
		this.direction = direction;
		this.contraindicated = contraindicated;
		this.caution = caution;
		this.sideEffect = sideEffect;
		this.distanceDiscontinued = distanceDiscontinued;
		this.mfgDate = mfgDate;
		this.expDate = expDate;
		this.productBy = productBy;
		this.note = note;
		this.image = image;
		this.barcode = barcode;
		this.medicineSuccess = medicineSuccess;
		this.medicineLost = medicineLost;
		this.treatmentHistories = treatmentHistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_medicine_id")
	public TypeMedicine getTypeMedicine() {
		return this.typeMedicine;
	}

	public void setTypeMedicine(TypeMedicine typeMedicine) {
		this.typeMedicine = typeMedicine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unit_medicine_id")
	public UnitMedicine getUnitMedicine() {
		return this.unitMedicine;
	}

	public void setUnitMedicine(UnitMedicine unitMedicine) {
		this.unitMedicine = unitMedicine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_medicine_id")
	public GroupMedicine getGroupMedicine() {
		return this.groupMedicine;
	}

	public void setGroupMedicine(GroupMedicine groupMedicine) {
		this.groupMedicine = groupMedicine;
	}

	@Column(name = "trade_name", length = 100)
	public String getTradeName() {
		return this.tradeName;
	}

	public void setTradeName(String tradeName) {
		this.tradeName = tradeName;
	}

	@Column(name = "scientific_name", length = 100)
	public String getScientificName() {
		return this.scientificName;
	}

	public void setScientificName(String scientificName) {
		this.scientificName = scientificName;
	}

	@Column(name = "common_name", length = 100)
	public String getCommonName() {
		return this.commonName;
	}

	public void setCommonName(String commonName) {
		this.commonName = commonName;
	}

	@Column(name = "qty", precision = 10, scale = 0)
	public Long getQty() {
		return this.qty;
	}

	public void setQty(Long qty) {
		this.qty = qty;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "ingredient", length = 1000)
	public String getIngredient() {
		return this.ingredient;
	}

	public void setIngredient(String ingredient) {
		this.ingredient = ingredient;
	}

	@Column(name = "properties", length = 1000)
	public String getProperties() {
		return this.properties;
	}

	public void setProperties(String properties) {
		this.properties = properties;
	}

	@Column(name = "instruction", length = 1000)
	public String getInstruction() {
		return this.instruction;
	}

	public void setInstruction(String instruction) {
		this.instruction = instruction;
	}

	@Column(name = "direction", length = 45)
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	@Column(name = "contraindicated", length = 400)
	public String getContraindicated() {
		return this.contraindicated;
	}

	public void setContraindicated(String contraindicated) {
		this.contraindicated = contraindicated;
	}

	@Column(name = "caution", length = 45)
	public String getCaution() {
		return this.caution;
	}

	public void setCaution(String caution) {
		this.caution = caution;
	}

	@Column(name = "side_effect", length = 45)
	public String getSideEffect() {
		return this.sideEffect;
	}

	public void setSideEffect(String sideEffect) {
		this.sideEffect = sideEffect;
	}

	@Column(name = "distance_discontinued", length = 100)
	public String getDistanceDiscontinued() {
		return this.distanceDiscontinued;
	}

	public void setDistanceDiscontinued(String distanceDiscontinued) {
		this.distanceDiscontinued = distanceDiscontinued;
	}

	@Column(name = "mfg_date", length = 10)
	public String getMfgDate() {
		return this.mfgDate;
	}

	public void setMfgDate(String mfgDate) {
		this.mfgDate = mfgDate;
	}

	@Column(name = "exp_date", length = 10)
	public String getExpDate() {
		return this.expDate;
	}

	public void setExpDate(String expDate) {
		this.expDate = expDate;
	}

	@Column(name = "product_by", length = 50)
	public String getProductBy() {
		return this.productBy;
	}

	public void setProductBy(String productBy) {
		this.productBy = productBy;
	}

	@Column(name = "note", length = 45)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "image", length = 100)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "barcode", length = 45)
	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	@Column(name = "medicine_success")
	public Integer getMedicineSuccess() {
		return this.medicineSuccess;
	}

	public void setMedicineSuccess(Integer medicineSuccess) {
		this.medicineSuccess = medicineSuccess;
	}

	@Column(name = "medicine_lost")
	public Integer getMedicineLost() {
		return this.medicineLost;
	}

	public void setMedicineLost(Integer medicineLost) {
		this.medicineLost = medicineLost;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medicine")
	public Set<TreatmentHistory> getTreatmentHistories() {
		return this.treatmentHistories;
	}

	public void setTreatmentHistories(Set<TreatmentHistory> treatmentHistories) {
		this.treatmentHistories = treatmentHistories;
	}

}
