// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private Integer id;
     private Privilege privilege;
     private String username;
     private String password;
     private String first;
     private String last;
     private Date birthday;
     private String age;
     private String sex;
     private String idCard;
     private String nationlity;
     private String tel;
     private String mobile;
     private String fax;
     private String address;
     private String zipcode;
     private String email;
     private String altEmail;
     private String image;
     private String question;
     private String answer;
     private Set toolBorrows = new HashSet(0);
     private Set cattleWeans = new HashSet(0);
     private Set breedings = new HashSet(0);
     private Set cattleYears = new HashSet(0);
     private Set treatmentHistories = new HashSet(0);
     private Set cattleStamps = new HashSet(0);
     private Set toolBrokens = new HashSet(0);
     private Set festivities = new HashSet(0);
     private Set semenOrders = new HashSet(0);
     private Set toolImports = new HashSet(0);
     private Set bills = new HashSet(0);
     private Set hornDeterings = new HashSet(0);
     private Set cattleFattens = new HashSet(0);
     private Set synchronizes = new HashSet(0);
     private Set formulaRecords = new HashSet(0);
     private Set semenImports = new HashSet(0);
     private Set semenReleases = new HashSet(0);
     private Set misscarries = new HashSet(0);
     private Set rawMaterialReleases = new HashSet(0);
     private Set cattleShows = new HashSet(0);
     private Set medicineImports = new HashSet(0);
     private Set toolReleases = new HashSet(0);
     private Set alerts = new HashSet(0);
     private Set medicineReleases = new HashSet(0);
     private Set rawMaterialImports = new HashSet(0);
     private Set cattleStrains = new HashSet(0);
     private Set rawMaterialOrders = new HashSet(0);
     private Set toolOrders = new HashSet(0);
     private Set diseases = new HashSet(0);
     private Set formulaRecord2s = new HashSet(0);
     private Set medicineOrders = new HashSet(0);
     private Set pregnants = new HashSet(0);

    public Member() {
    }

	
    public Member(Privilege privilege) {
        this.privilege = privilege;
    }
    public Member(Privilege privilege, String username, String password, String first, String last, Date birthday, String age, String sex, String idCard, String nationlity, String tel, String mobile, String fax, String address, String zipcode, String email, String altEmail, String image, String question, String answer, Set toolBorrows, Set cattleWeans, Set breedings, Set cattleYears, Set treatmentHistories, Set cattleStamps, Set toolBrokens, Set festivities, Set semenOrders, Set toolImports, Set bills, Set hornDeterings, Set cattleFattens, Set synchronizes, Set formulaRecords, Set semenImports, Set semenReleases, Set misscarries, Set rawMaterialReleases, Set cattleShows, Set medicineImports, Set toolReleases, Set alerts, Set medicineReleases, Set rawMaterialImports, Set cattleStrains, Set rawMaterialOrders, Set toolOrders, Set diseases, Set formulaRecord2s, Set medicineOrders, Set pregnants) {
       this.privilege = privilege;
       this.username = username;
       this.password = password;
       this.first = first;
       this.last = last;
       this.birthday = birthday;
       this.age = age;
       this.sex = sex;
       this.idCard = idCard;
       this.nationlity = nationlity;
       this.tel = tel;
       this.mobile = mobile;
       this.fax = fax;
       this.address = address;
       this.zipcode = zipcode;
       this.email = email;
       this.altEmail = altEmail;
       this.image = image;
       this.question = question;
       this.answer = answer;
       this.toolBorrows = toolBorrows;
       this.cattleWeans = cattleWeans;
       this.breedings = breedings;
       this.cattleYears = cattleYears;
       this.treatmentHistories = treatmentHistories;
       this.cattleStamps = cattleStamps;
       this.toolBrokens = toolBrokens;
       this.festivities = festivities;
       this.semenOrders = semenOrders;
       this.toolImports = toolImports;
       this.bills = bills;
       this.hornDeterings = hornDeterings;
       this.cattleFattens = cattleFattens;
       this.synchronizes = synchronizes;
       this.formulaRecords = formulaRecords;
       this.semenImports = semenImports;
       this.semenReleases = semenReleases;
       this.misscarries = misscarries;
       this.rawMaterialReleases = rawMaterialReleases;
       this.cattleShows = cattleShows;
       this.medicineImports = medicineImports;
       this.toolReleases = toolReleases;
       this.alerts = alerts;
       this.medicineReleases = medicineReleases;
       this.rawMaterialImports = rawMaterialImports;
       this.cattleStrains = cattleStrains;
       this.rawMaterialOrders = rawMaterialOrders;
       this.toolOrders = toolOrders;
       this.diseases = diseases;
       this.formulaRecord2s = formulaRecord2s;
       this.medicineOrders = medicineOrders;
       this.pregnants = pregnants;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Privilege getPrivilege() {
        return this.privilege;
    }
    
    public void setPrivilege(Privilege privilege) {
        this.privilege = privilege;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirst() {
        return this.first;
    }
    
    public void setFirst(String first) {
        this.first = first;
    }
    public String getLast() {
        return this.last;
    }
    
    public void setLast(String last) {
        this.last = last;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getIdCard() {
        return this.idCard;
    }
    
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }
    public String getNationlity() {
        return this.nationlity;
    }
    
    public void setNationlity(String nationlity) {
        this.nationlity = nationlity;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAltEmail() {
        return this.altEmail;
    }
    
    public void setAltEmail(String altEmail) {
        this.altEmail = altEmail;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public Set getToolBorrows() {
        return this.toolBorrows;
    }
    
    public void setToolBorrows(Set toolBorrows) {
        this.toolBorrows = toolBorrows;
    }
    public Set getCattleWeans() {
        return this.cattleWeans;
    }
    
    public void setCattleWeans(Set cattleWeans) {
        this.cattleWeans = cattleWeans;
    }
    public Set getBreedings() {
        return this.breedings;
    }
    
    public void setBreedings(Set breedings) {
        this.breedings = breedings;
    }
    public Set getCattleYears() {
        return this.cattleYears;
    }
    
    public void setCattleYears(Set cattleYears) {
        this.cattleYears = cattleYears;
    }
    public Set getTreatmentHistories() {
        return this.treatmentHistories;
    }
    
    public void setTreatmentHistories(Set treatmentHistories) {
        this.treatmentHistories = treatmentHistories;
    }
    public Set getCattleStamps() {
        return this.cattleStamps;
    }
    
    public void setCattleStamps(Set cattleStamps) {
        this.cattleStamps = cattleStamps;
    }
    public Set getToolBrokens() {
        return this.toolBrokens;
    }
    
    public void setToolBrokens(Set toolBrokens) {
        this.toolBrokens = toolBrokens;
    }
    public Set getFestivities() {
        return this.festivities;
    }
    
    public void setFestivities(Set festivities) {
        this.festivities = festivities;
    }
    public Set getSemenOrders() {
        return this.semenOrders;
    }
    
    public void setSemenOrders(Set semenOrders) {
        this.semenOrders = semenOrders;
    }
    public Set getToolImports() {
        return this.toolImports;
    }
    
    public void setToolImports(Set toolImports) {
        this.toolImports = toolImports;
    }
    public Set getBills() {
        return this.bills;
    }
    
    public void setBills(Set bills) {
        this.bills = bills;
    }
    public Set getHornDeterings() {
        return this.hornDeterings;
    }
    
    public void setHornDeterings(Set hornDeterings) {
        this.hornDeterings = hornDeterings;
    }
    public Set getCattleFattens() {
        return this.cattleFattens;
    }
    
    public void setCattleFattens(Set cattleFattens) {
        this.cattleFattens = cattleFattens;
    }
    public Set getSynchronizes() {
        return this.synchronizes;
    }
    
    public void setSynchronizes(Set synchronizes) {
        this.synchronizes = synchronizes;
    }
    public Set getFormulaRecords() {
        return this.formulaRecords;
    }
    
    public void setFormulaRecords(Set formulaRecords) {
        this.formulaRecords = formulaRecords;
    }
    public Set getSemenImports() {
        return this.semenImports;
    }
    
    public void setSemenImports(Set semenImports) {
        this.semenImports = semenImports;
    }
    public Set getSemenReleases() {
        return this.semenReleases;
    }
    
    public void setSemenReleases(Set semenReleases) {
        this.semenReleases = semenReleases;
    }
    public Set getMisscarries() {
        return this.misscarries;
    }
    
    public void setMisscarries(Set misscarries) {
        this.misscarries = misscarries;
    }
    public Set getRawMaterialReleases() {
        return this.rawMaterialReleases;
    }
    
    public void setRawMaterialReleases(Set rawMaterialReleases) {
        this.rawMaterialReleases = rawMaterialReleases;
    }
    public Set getCattleShows() {
        return this.cattleShows;
    }
    
    public void setCattleShows(Set cattleShows) {
        this.cattleShows = cattleShows;
    }
    public Set getMedicineImports() {
        return this.medicineImports;
    }
    
    public void setMedicineImports(Set medicineImports) {
        this.medicineImports = medicineImports;
    }
    public Set getToolReleases() {
        return this.toolReleases;
    }
    
    public void setToolReleases(Set toolReleases) {
        this.toolReleases = toolReleases;
    }
    public Set getAlerts() {
        return this.alerts;
    }
    
    public void setAlerts(Set alerts) {
        this.alerts = alerts;
    }
    public Set getMedicineReleases() {
        return this.medicineReleases;
    }
    
    public void setMedicineReleases(Set medicineReleases) {
        this.medicineReleases = medicineReleases;
    }
    public Set getRawMaterialImports() {
        return this.rawMaterialImports;
    }
    
    public void setRawMaterialImports(Set rawMaterialImports) {
        this.rawMaterialImports = rawMaterialImports;
    }
    public Set getCattleStrains() {
        return this.cattleStrains;
    }
    
    public void setCattleStrains(Set cattleStrains) {
        this.cattleStrains = cattleStrains;
    }
    public Set getRawMaterialOrders() {
        return this.rawMaterialOrders;
    }
    
    public void setRawMaterialOrders(Set rawMaterialOrders) {
        this.rawMaterialOrders = rawMaterialOrders;
    }
    public Set getToolOrders() {
        return this.toolOrders;
    }
    
    public void setToolOrders(Set toolOrders) {
        this.toolOrders = toolOrders;
    }
    public Set getDiseases() {
        return this.diseases;
    }
    
    public void setDiseases(Set diseases) {
        this.diseases = diseases;
    }
    public Set getFormulaRecord2s() {
        return this.formulaRecord2s;
    }
    
    public void setFormulaRecord2s(Set formulaRecord2s) {
        this.formulaRecord2s = formulaRecord2s;
    }
    public Set getMedicineOrders() {
        return this.medicineOrders;
    }
    
    public void setMedicineOrders(Set medicineOrders) {
        this.medicineOrders = medicineOrders;
    }
    public Set getPregnants() {
        return this.pregnants;
    }
    
    public void setPregnants(Set pregnants) {
        this.pregnants = pregnants;
    }




}


