// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * Misscarry generated by hbm2java
 */
public class Misscarry  implements java.io.Serializable {


     private Integer id;
     private Cattle cattle;
     private Member member;
     private String countMisscarry;
     private Date day;
     private String note;
     private String causeMisscary;

    public Misscarry() {
    }

    public Misscarry(Cattle cattle, Member member, String countMisscarry, Date day, String note, String causeMisscary) {
       this.cattle = cattle;
       this.member = member;
       this.countMisscarry = countMisscarry;
       this.day = day;
       this.note = note;
       this.causeMisscary = causeMisscary;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cattle getCattle() {
        return this.cattle;
    }
    
    public void setCattle(Cattle cattle) {
        this.cattle = cattle;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public String getCountMisscarry() {
        return this.countMisscarry;
    }
    
    public void setCountMisscarry(String countMisscarry) {
        this.countMisscarry = countMisscarry;
    }
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getCauseMisscary() {
        return this.causeMisscary;
    }
    
    public void setCauseMisscary(String causeMisscary) {
        this.causeMisscary = causeMisscary;
    }




}


