package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Misscarry generated by hbm2java
 */
@Entity
@Table(name = "misscarry", catalog = "induct")
public class Misscarry implements java.io.Serializable {

	private Integer id;
	private Cattle cattle;
	private Member member;
	private String countMisscarry;
	private String day;
	private String note;

	public Misscarry() {
	}

	public Misscarry(Cattle cattle, Member member, String countMisscarry, String day, String note) {
		this.cattle = cattle;
		this.member = member;
		this.countMisscarry = countMisscarry;
		this.day = day;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cattle_id")
	public Cattle getCattle() {
		return this.cattle;
	}

	public void setCattle(Cattle cattle) {
		this.cattle = cattle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "count_misscarry", length = 50)
	public String getCountMisscarry() {
		return this.countMisscarry;
	}

	public void setCountMisscarry(String countMisscarry) {
		this.countMisscarry = countMisscarry;
	}

	@Column(name = "day", length = 10)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Column(name = "note", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
