// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * Pregnant generated by hbm2java
 */
public class Pregnant  implements java.io.Serializable {


     private Integer id;
     private Breeding breeding;
     private Member member;
     private StatusPregnant statusPregnant;
     private Date datePreg;
     private Date dateSchedule;
     private Date timePreg;
     private String note;
     private String cattle;
     private Integer stat;

    public Pregnant() {
    }

    public Pregnant(Breeding breeding, Member member, StatusPregnant statusPregnant, Date datePreg, Date dateSchedule, Date timePreg, String note, String cattle, Integer stat) {
       this.breeding = breeding;
       this.member = member;
       this.statusPregnant = statusPregnant;
       this.datePreg = datePreg;
       this.dateSchedule = dateSchedule;
       this.timePreg = timePreg;
       this.note = note;
       this.cattle = cattle;
       this.stat = stat;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Breeding getBreeding() {
        return this.breeding;
    }
    
    public void setBreeding(Breeding breeding) {
        this.breeding = breeding;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public StatusPregnant getStatusPregnant() {
        return this.statusPregnant;
    }
    
    public void setStatusPregnant(StatusPregnant statusPregnant) {
        this.statusPregnant = statusPregnant;
    }
    public Date getDatePreg() {
        return this.datePreg;
    }
    
    public void setDatePreg(Date datePreg) {
        this.datePreg = datePreg;
    }
    public Date getDateSchedule() {
        return this.dateSchedule;
    }
    
    public void setDateSchedule(Date dateSchedule) {
        this.dateSchedule = dateSchedule;
    }
    public Date getTimePreg() {
        return this.timePreg;
    }
    
    public void setTimePreg(Date timePreg) {
        this.timePreg = timePreg;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getCattle() {
        return this.cattle;
    }
    
    public void setCattle(String cattle) {
        this.cattle = cattle;
    }
    public Integer getStat() {
        return this.stat;
    }
    
    public void setStat(Integer stat) {
        this.stat = stat;
    }




}


