package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pregnant generated by hbm2java
 */
@Entity
@Table(name = "pregnant", catalog = "induct")
public class Pregnant implements java.io.Serializable {

	private Integer id;
	private StatusPregnant statusPregnant;
	private Breeding breeding;
	private Member member;
	private String datePreg;
	private String dateSchedule;
	private String timePreg;
	private String note;
	private String dateAlertdao;
	private String dateAlertdao1;
	private String dateAlertdao2;
	private String dateAlertdao3;
	private String cattle;
	private Integer stat;

	public Pregnant() {
	}

	public Pregnant(StatusPregnant statusPregnant, Breeding breeding, Member member, String datePreg, String dateSchedule,
			String timePreg, String note, String dateAlertdao, String dateAlertdao1, String dateAlertdao2, String dateAlertdao3,
			String cattle, Integer stat) {
		this.statusPregnant = statusPregnant;
		this.breeding = breeding;
		this.member = member;
		this.datePreg = datePreg;
		this.dateSchedule = dateSchedule;
		this.timePreg = timePreg;
		this.note = note;
		this.dateAlertdao = dateAlertdao;
		this.dateAlertdao1 = dateAlertdao1;
		this.dateAlertdao2 = dateAlertdao2;
		this.dateAlertdao3 = dateAlertdao3;
		this.cattle = cattle;
		this.stat = stat;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_pregnant_id")
	public StatusPregnant getStatusPregnant() {
		return this.statusPregnant;
	}

	public void setStatusPregnant(StatusPregnant statusPregnant) {
		this.statusPregnant = statusPregnant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "breeding_id")
	public Breeding getBreeding() {
		return this.breeding;
	}

	public void setBreeding(Breeding breeding) {
		this.breeding = breeding;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}


	@Column(name = "date_preg", length = 10)
	public String getDatePreg() {
		return this.datePreg;
	}

	public void setDatePreg(String datePreg) {
		this.datePreg = datePreg;
	}


	@Column(name = "date_schedule", length = 19)
	public String getDateSchedule() {
		return this.dateSchedule;
	}

	public void setDateSchedule(String dateSchedule) {
		this.dateSchedule = dateSchedule;
	}


	@Column(name = "time_preg", length = 8)
	public String getTimePreg() {
		return this.timePreg;
	}

	public void setTimePreg(String timePreg) {
		this.timePreg = timePreg;
	}

	@Column(name = "note", length = 100)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}


	@Column(name = "date_alertdao", length = 10)
	public String getDateAlertdao() {
		return this.dateAlertdao;
	}

	public void setDateAlertdao(String dateAlertdao) {
		this.dateAlertdao = dateAlertdao;
	}

	
	@Column(name = "date_alertdao1", length = 10)
	public String getDateAlertdao1() {
		return this.dateAlertdao1;
	}

	public void setDateAlertdao1(String dateAlertdao1) {
		this.dateAlertdao1 = dateAlertdao1;
	}


	@Column(name = "date_alertdao2", length = 10)
	public String getDateAlertdao2() {
		return this.dateAlertdao2;
	}

	public void setDateAlertdao2(String dateAlertdao2) {
		this.dateAlertdao2 = dateAlertdao2;
	}

	
	@Column(name = "date_alertdao3", length = 10)
	public String getDateAlertdao3() {
		return this.dateAlertdao3;
	}

	public void setDateAlertdao3(String dateAlertdao3) {
		this.dateAlertdao3 = dateAlertdao3;
	}

	@Column(name = "cattle", length = 50)
	public String getCattle() {
		return this.cattle;
	}

	public void setCattle(String cattle) {
		this.cattle = cattle;
	}

	@Column(name = "stat")
	public Integer getStat() {
		return this.stat;
	}

	public void setStat(Integer stat) {
		this.stat = stat;
	}

}
