// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Privilege generated by hbm2java
 */
public class Privilege  implements java.io.Serializable {


     private Integer id;
     private String value;
     private int permitAddMed;
     private int permitImportMed;
     private int permitReleaseMed;
     private int permitOrderMed;
     private int permitAddSemen;
     private int permitImportSemen;
     private int permitReleaseSemen;
     private int permitOrderSemen;
     private int permitAddRaw;
     private int permitImportRaw;
     private int permitReleaseRaw;
     private int permitOrderRaw;
     private int permitAddTool;
     private int permitImportTool;
     private int permitReleaseTool;
     private int permitBorrowTool;
     private int permitOrderTool;
     private int permitSetting;
     private int permitSms;
     private Set members = new HashSet(0);

    public Privilege() {
    }

	
    public Privilege(String value, int permitAddMed, int permitImportMed, int permitReleaseMed, int permitOrderMed, int permitAddSemen, int permitImportSemen, int permitReleaseSemen, int permitOrderSemen, int permitAddRaw, int permitImportRaw, int permitReleaseRaw, int permitOrderRaw, int permitAddTool, int permitImportTool, int permitReleaseTool, int permitBorrowTool, int permitOrderTool, int permitSetting, int permitSms) {
        this.value = value;
        this.permitAddMed = permitAddMed;
        this.permitImportMed = permitImportMed;
        this.permitReleaseMed = permitReleaseMed;
        this.permitOrderMed = permitOrderMed;
        this.permitAddSemen = permitAddSemen;
        this.permitImportSemen = permitImportSemen;
        this.permitReleaseSemen = permitReleaseSemen;
        this.permitOrderSemen = permitOrderSemen;
        this.permitAddRaw = permitAddRaw;
        this.permitImportRaw = permitImportRaw;
        this.permitReleaseRaw = permitReleaseRaw;
        this.permitOrderRaw = permitOrderRaw;
        this.permitAddTool = permitAddTool;
        this.permitImportTool = permitImportTool;
        this.permitReleaseTool = permitReleaseTool;
        this.permitBorrowTool = permitBorrowTool;
        this.permitOrderTool = permitOrderTool;
        this.permitSetting = permitSetting;
        this.permitSms = permitSms;
    }
    public Privilege(String value, int permitAddMed, int permitImportMed, int permitReleaseMed, int permitOrderMed, int permitAddSemen, int permitImportSemen, int permitReleaseSemen, int permitOrderSemen, int permitAddRaw, int permitImportRaw, int permitReleaseRaw, int permitOrderRaw, int permitAddTool, int permitImportTool, int permitReleaseTool, int permitBorrowTool, int permitOrderTool, int permitSetting, int permitSms, Set members) {
       this.value = value;
       this.permitAddMed = permitAddMed;
       this.permitImportMed = permitImportMed;
       this.permitReleaseMed = permitReleaseMed;
       this.permitOrderMed = permitOrderMed;
       this.permitAddSemen = permitAddSemen;
       this.permitImportSemen = permitImportSemen;
       this.permitReleaseSemen = permitReleaseSemen;
       this.permitOrderSemen = permitOrderSemen;
       this.permitAddRaw = permitAddRaw;
       this.permitImportRaw = permitImportRaw;
       this.permitReleaseRaw = permitReleaseRaw;
       this.permitOrderRaw = permitOrderRaw;
       this.permitAddTool = permitAddTool;
       this.permitImportTool = permitImportTool;
       this.permitReleaseTool = permitReleaseTool;
       this.permitBorrowTool = permitBorrowTool;
       this.permitOrderTool = permitOrderTool;
       this.permitSetting = permitSetting;
       this.permitSms = permitSms;
       this.members = members;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public int getPermitAddMed() {
        return this.permitAddMed;
    }
    
    public void setPermitAddMed(int permitAddMed) {
        this.permitAddMed = permitAddMed;
    }
    public int getPermitImportMed() {
        return this.permitImportMed;
    }
    
    public void setPermitImportMed(int permitImportMed) {
        this.permitImportMed = permitImportMed;
    }
    public int getPermitReleaseMed() {
        return this.permitReleaseMed;
    }
    
    public void setPermitReleaseMed(int permitReleaseMed) {
        this.permitReleaseMed = permitReleaseMed;
    }
    public int getPermitOrderMed() {
        return this.permitOrderMed;
    }
    
    public void setPermitOrderMed(int permitOrderMed) {
        this.permitOrderMed = permitOrderMed;
    }
    public int getPermitAddSemen() {
        return this.permitAddSemen;
    }
    
    public void setPermitAddSemen(int permitAddSemen) {
        this.permitAddSemen = permitAddSemen;
    }
    public int getPermitImportSemen() {
        return this.permitImportSemen;
    }
    
    public void setPermitImportSemen(int permitImportSemen) {
        this.permitImportSemen = permitImportSemen;
    }
    public int getPermitReleaseSemen() {
        return this.permitReleaseSemen;
    }
    
    public void setPermitReleaseSemen(int permitReleaseSemen) {
        this.permitReleaseSemen = permitReleaseSemen;
    }
    public int getPermitOrderSemen() {
        return this.permitOrderSemen;
    }
    
    public void setPermitOrderSemen(int permitOrderSemen) {
        this.permitOrderSemen = permitOrderSemen;
    }
    public int getPermitAddRaw() {
        return this.permitAddRaw;
    }
    
    public void setPermitAddRaw(int permitAddRaw) {
        this.permitAddRaw = permitAddRaw;
    }
    public int getPermitImportRaw() {
        return this.permitImportRaw;
    }
    
    public void setPermitImportRaw(int permitImportRaw) {
        this.permitImportRaw = permitImportRaw;
    }
    public int getPermitReleaseRaw() {
        return this.permitReleaseRaw;
    }
    
    public void setPermitReleaseRaw(int permitReleaseRaw) {
        this.permitReleaseRaw = permitReleaseRaw;
    }
    public int getPermitOrderRaw() {
        return this.permitOrderRaw;
    }
    
    public void setPermitOrderRaw(int permitOrderRaw) {
        this.permitOrderRaw = permitOrderRaw;
    }
    public int getPermitAddTool() {
        return this.permitAddTool;
    }
    
    public void setPermitAddTool(int permitAddTool) {
        this.permitAddTool = permitAddTool;
    }
    public int getPermitImportTool() {
        return this.permitImportTool;
    }
    
    public void setPermitImportTool(int permitImportTool) {
        this.permitImportTool = permitImportTool;
    }
    public int getPermitReleaseTool() {
        return this.permitReleaseTool;
    }
    
    public void setPermitReleaseTool(int permitReleaseTool) {
        this.permitReleaseTool = permitReleaseTool;
    }
    public int getPermitBorrowTool() {
        return this.permitBorrowTool;
    }
    
    public void setPermitBorrowTool(int permitBorrowTool) {
        this.permitBorrowTool = permitBorrowTool;
    }
    public int getPermitOrderTool() {
        return this.permitOrderTool;
    }
    
    public void setPermitOrderTool(int permitOrderTool) {
        this.permitOrderTool = permitOrderTool;
    }
    public int getPermitSetting() {
        return this.permitSetting;
    }
    
    public void setPermitSetting(int permitSetting) {
        this.permitSetting = permitSetting;
    }
    public int getPermitSms() {
        return this.permitSms;
    }
    
    public void setPermitSms(int permitSms) {
        this.permitSms = permitSms;
    }
    public Set getMembers() {
        return this.members;
    }
    
    public void setMembers(Set members) {
        this.members = members;
    }




}


