// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * RawMaterialNutrient generated by hbm2java
 */
public class RawMaterialNutrient  implements java.io.Serializable {


     private Integer id;
     private RawMaterial rawMaterial;
     private UnitNutrient unitNutrient;
     private Date date;
     private Float protein;
     private Float tdn;
     private Float nfc;
     private Float dm;
     private Float uip;
     private Float dip;
     private Float ca;
     private Float p;
     private Float urea;
     private Float cl;
     private Float k;
     private Float s;
     private Float mg;
     private Float zn;
     private Float cu;
     private Float mn;
     private Float co;
     private Float se;
     private Float i;
     private Float vitA;
     private Float vitD;
     private Float vitE;
     private Float nel;
     private Float nem;
     private Float neg;
     private Float ndf;
     private Float ee;
     private Float cp;
     private Float cf;
     private Float ash;
     private Float nfe;
     private Float adf;
     private Float adl;
     private Float de;
     private Float me;
     private Float na;
     private Float fe;

    public RawMaterialNutrient() {
    }

    public RawMaterialNutrient(RawMaterial rawMaterial, UnitNutrient unitNutrient, Date date, Float protein, Float tdn, Float nfc, Float dm, Float uip, Float dip, Float ca, Float p, Float urea, Float cl, Float k, Float s, Float mg, Float zn, Float cu, Float mn, Float co, Float se, Float i, Float vitA, Float vitD, Float vitE, Float nel, Float nem, Float neg, Float ndf, Float ee, Float cp, Float cf, Float ash, Float nfe, Float adf, Float adl, Float de, Float me, Float na, Float fe) {
       this.rawMaterial = rawMaterial;
       this.unitNutrient = unitNutrient;
       this.date = date;
       this.protein = protein;
       this.tdn = tdn;
       this.nfc = nfc;
       this.dm = dm;
       this.uip = uip;
       this.dip = dip;
       this.ca = ca;
       this.p = p;
       this.urea = urea;
       this.cl = cl;
       this.k = k;
       this.s = s;
       this.mg = mg;
       this.zn = zn;
       this.cu = cu;
       this.mn = mn;
       this.co = co;
       this.se = se;
       this.i = i;
       this.vitA = vitA;
       this.vitD = vitD;
       this.vitE = vitE;
       this.nel = nel;
       this.nem = nem;
       this.neg = neg;
       this.ndf = ndf;
       this.ee = ee;
       this.cp = cp;
       this.cf = cf;
       this.ash = ash;
       this.nfe = nfe;
       this.adf = adf;
       this.adl = adl;
       this.de = de;
       this.me = me;
       this.na = na;
       this.fe = fe;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public RawMaterial getRawMaterial() {
        return this.rawMaterial;
    }
    
    public void setRawMaterial(RawMaterial rawMaterial) {
        this.rawMaterial = rawMaterial;
    }
    public UnitNutrient getUnitNutrient() {
        return this.unitNutrient;
    }
    
    public void setUnitNutrient(UnitNutrient unitNutrient) {
        this.unitNutrient = unitNutrient;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Float getProtein() {
        return this.protein;
    }
    
    public void setProtein(Float protein) {
        this.protein = protein;
    }
    public Float getTdn() {
        return this.tdn;
    }
    
    public void setTdn(Float tdn) {
        this.tdn = tdn;
    }
    public Float getNfc() {
        return this.nfc;
    }
    
    public void setNfc(Float nfc) {
        this.nfc = nfc;
    }
    public Float getDm() {
        return this.dm;
    }
    
    public void setDm(Float dm) {
        this.dm = dm;
    }
    public Float getUip() {
        return this.uip;
    }
    
    public void setUip(Float uip) {
        this.uip = uip;
    }
    public Float getDip() {
        return this.dip;
    }
    
    public void setDip(Float dip) {
        this.dip = dip;
    }
    public Float getCa() {
        return this.ca;
    }
    
    public void setCa(Float ca) {
        this.ca = ca;
    }
    public Float getP() {
        return this.p;
    }
    
    public void setP(Float p) {
        this.p = p;
    }
    public Float getUrea() {
        return this.urea;
    }
    
    public void setUrea(Float urea) {
        this.urea = urea;
    }
    public Float getCl() {
        return this.cl;
    }
    
    public void setCl(Float cl) {
        this.cl = cl;
    }
    public Float getK() {
        return this.k;
    }
    
    public void setK(Float k) {
        this.k = k;
    }
    public Float getS() {
        return this.s;
    }
    
    public void setS(Float s) {
        this.s = s;
    }
    public Float getMg() {
        return this.mg;
    }
    
    public void setMg(Float mg) {
        this.mg = mg;
    }
    public Float getZn() {
        return this.zn;
    }
    
    public void setZn(Float zn) {
        this.zn = zn;
    }
    public Float getCu() {
        return this.cu;
    }
    
    public void setCu(Float cu) {
        this.cu = cu;
    }
    public Float getMn() {
        return this.mn;
    }
    
    public void setMn(Float mn) {
        this.mn = mn;
    }
    public Float getCo() {
        return this.co;
    }
    
    public void setCo(Float co) {
        this.co = co;
    }
    public Float getSe() {
        return this.se;
    }
    
    public void setSe(Float se) {
        this.se = se;
    }
    public Float getI() {
        return this.i;
    }
    
    public void setI(Float i) {
        this.i = i;
    }
    public Float getVitA() {
        return this.vitA;
    }
    
    public void setVitA(Float vitA) {
        this.vitA = vitA;
    }
    public Float getVitD() {
        return this.vitD;
    }
    
    public void setVitD(Float vitD) {
        this.vitD = vitD;
    }
    public Float getVitE() {
        return this.vitE;
    }
    
    public void setVitE(Float vitE) {
        this.vitE = vitE;
    }
    public Float getNel() {
        return this.nel;
    }
    
    public void setNel(Float nel) {
        this.nel = nel;
    }
    public Float getNem() {
        return this.nem;
    }
    
    public void setNem(Float nem) {
        this.nem = nem;
    }
    public Float getNeg() {
        return this.neg;
    }
    
    public void setNeg(Float neg) {
        this.neg = neg;
    }
    public Float getNdf() {
        return this.ndf;
    }
    
    public void setNdf(Float ndf) {
        this.ndf = ndf;
    }
    public Float getEe() {
        return this.ee;
    }
    
    public void setEe(Float ee) {
        this.ee = ee;
    }
    public Float getCp() {
        return this.cp;
    }
    
    public void setCp(Float cp) {
        this.cp = cp;
    }
    public Float getCf() {
        return this.cf;
    }
    
    public void setCf(Float cf) {
        this.cf = cf;
    }
    public Float getAsh() {
        return this.ash;
    }
    
    public void setAsh(Float ash) {
        this.ash = ash;
    }
    public Float getNfe() {
        return this.nfe;
    }
    
    public void setNfe(Float nfe) {
        this.nfe = nfe;
    }
    public Float getAdf() {
        return this.adf;
    }
    
    public void setAdf(Float adf) {
        this.adf = adf;
    }
    public Float getAdl() {
        return this.adl;
    }
    
    public void setAdl(Float adl) {
        this.adl = adl;
    }
    public Float getDe() {
        return this.de;
    }
    
    public void setDe(Float de) {
        this.de = de;
    }
    public Float getMe() {
        return this.me;
    }
    
    public void setMe(Float me) {
        this.me = me;
    }
    public Float getNa() {
        return this.na;
    }
    
    public void setNa(Float na) {
        this.na = na;
    }
    public Float getFe() {
        return this.fe;
    }
    
    public void setFe(Float fe) {
        this.fe = fe;
    }




}


