// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * RawMaterialOrder generated by hbm2java
 */
public class RawMaterialOrder  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private RawMaterial rawMaterial;
     private Integer quantity;
     private Integer billId;
     private Date day;

    public RawMaterialOrder() {
    }

	
    public RawMaterialOrder(Member member, RawMaterial rawMaterial, Date day) {
        this.member = member;
        this.rawMaterial = rawMaterial;
        this.day = day;
    }
    public RawMaterialOrder(Member member, RawMaterial rawMaterial, Integer quantity, Integer billId, Date day) {
       this.member = member;
       this.rawMaterial = rawMaterial;
       this.quantity = quantity;
       this.billId = billId;
       this.day = day;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public RawMaterial getRawMaterial() {
        return this.rawMaterial;
    }
    
    public void setRawMaterial(RawMaterial rawMaterial) {
        this.rawMaterial = rawMaterial;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Integer getBillId() {
        return this.billId;
    }
    
    public void setBillId(Integer billId) {
        this.billId = billId;
    }
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }




}


