// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * RawMaterialRelease generated by hbm2java
 */
public class RawMaterialRelease  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private RawMaterial rawMaterial;
     private Date day;
     private int quantity;
     private Integer billId;

    public RawMaterialRelease() {
    }

	
    public RawMaterialRelease(Member member, RawMaterial rawMaterial, Date day, int quantity) {
        this.member = member;
        this.rawMaterial = rawMaterial;
        this.day = day;
        this.quantity = quantity;
    }
    public RawMaterialRelease(Member member, RawMaterial rawMaterial, Date day, int quantity, Integer billId) {
       this.member = member;
       this.rawMaterial = rawMaterial;
       this.day = day;
       this.quantity = quantity;
       this.billId = billId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public RawMaterial getRawMaterial() {
        return this.rawMaterial;
    }
    
    public void setRawMaterial(RawMaterial rawMaterial) {
        this.rawMaterial = rawMaterial;
    }
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Integer getBillId() {
        return this.billId;
    }
    
    public void setBillId(Integer billId) {
        this.billId = billId;
    }




}


