// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * RawMaterialImport generated by hbm2java
 */
public class RawMaterialImport  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private RawMaterial rawMaterial;
     private Integer lot;
     private Integer quantity;
     private Integer price;
     private Date dayMfd;
     private Date dayExp;
     private String import_;
     private String place;
     private Integer billId;
     private Integer beforeQuantity;
     private Date day;
     private int status;

    public RawMaterialImport() {
    }

	
    public RawMaterialImport(int status) {
        this.status = status;
    }
    public RawMaterialImport(Member member, RawMaterial rawMaterial, Integer lot, Integer quantity, Integer price, Date dayMfd, Date dayExp, String import_, String place, Integer billId, Integer beforeQuantity, Date day, int status) {
       this.member = member;
       this.rawMaterial = rawMaterial;
       this.lot = lot;
       this.quantity = quantity;
       this.price = price;
       this.dayMfd = dayMfd;
       this.dayExp = dayExp;
       this.import_ = import_;
       this.place = place;
       this.billId = billId;
       this.beforeQuantity = beforeQuantity;
       this.day = day;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public RawMaterial getRawMaterial() {
        return this.rawMaterial;
    }
    
    public void setRawMaterial(RawMaterial rawMaterial) {
        this.rawMaterial = rawMaterial;
    }
    public Integer getLot() {
        return this.lot;
    }
    
    public void setLot(Integer lot) {
        this.lot = lot;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Date getDayMfd() {
        return this.dayMfd;
    }
    
    public void setDayMfd(Date dayMfd) {
        this.dayMfd = dayMfd;
    }
    public Date getDayExp() {
        return this.dayExp;
    }
    
    public void setDayExp(Date dayExp) {
        this.dayExp = dayExp;
    }
    public String getImport_() {
        return this.import_;
    }
    
    public void setImport_(String import_) {
        this.import_ = import_;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    public Integer getBillId() {
        return this.billId;
    }
    
    public void setBillId(Integer billId) {
        this.billId = billId;
    }
    public Integer getBeforeQuantity() {
        return this.beforeQuantity;
    }
    
    public void setBeforeQuantity(Integer beforeQuantity) {
        this.beforeQuantity = beforeQuantity;
    }
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


