// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final



/**
 * RawMaterialPrice generated by hbm2java
 */
public class RawMaterialPrice  implements java.io.Serializable {


     private Integer id;
     private RawMaterial rawMaterial;
     private String username;
     private Float price;
     private String unit;

    public RawMaterialPrice() {
    }

    public RawMaterialPrice(RawMaterial rawMaterial, String username, Float price, String unit) {
       this.rawMaterial = rawMaterial;
       this.username = username;
       this.price = price;
       this.unit = unit;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public RawMaterial getRawMaterial() {
        return this.rawMaterial;
    }
    
    public void setRawMaterial(RawMaterial rawMaterial) {
        this.rawMaterial = rawMaterial;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }




}


