// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final



/**
 * RawMaterialFormula generated by hbm2java
 */
public class RawMaterialFormula  implements java.io.Serializable {


     private Integer id;
     private FormulaRecord formulaRecord;
     private FormulaRecord2 formulaRecord2;
     private String name;
     private Float value;
     private Float price;
     private Float dm;
     private Float cp;
     private Float tdn;
     private Float ndf;
     private Float vita;
     private Float vite;

    public RawMaterialFormula() {
    }

    public RawMaterialFormula(FormulaRecord formulaRecord, FormulaRecord2 formulaRecord2, String name, Float value, Float price, Float dm, Float cp, Float tdn, Float ndf, Float vita, Float vite) {
       this.formulaRecord = formulaRecord;
       this.formulaRecord2 = formulaRecord2;
       this.name = name;
       this.value = value;
       this.price = price;
       this.dm = dm;
       this.cp = cp;
       this.tdn = tdn;
       this.ndf = ndf;
       this.vita = vita;
       this.vite = vite;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public FormulaRecord getFormulaRecord() {
        return this.formulaRecord;
    }
    
    public void setFormulaRecord(FormulaRecord formulaRecord) {
        this.formulaRecord = formulaRecord;
    }
    public FormulaRecord2 getFormulaRecord2() {
        return this.formulaRecord2;
    }
    
    public void setFormulaRecord2(FormulaRecord2 formulaRecord2) {
        this.formulaRecord2 = formulaRecord2;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Float getValue() {
        return this.value;
    }
    
    public void setValue(Float value) {
        this.value = value;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }
    public Float getDm() {
        return this.dm;
    }
    
    public void setDm(Float dm) {
        this.dm = dm;
    }
    public Float getCp() {
        return this.cp;
    }
    
    public void setCp(Float cp) {
        this.cp = cp;
    }
    public Float getTdn() {
        return this.tdn;
    }
    
    public void setTdn(Float tdn) {
        this.tdn = tdn;
    }
    public Float getNdf() {
        return this.ndf;
    }
    
    public void setNdf(Float ndf) {
        this.ndf = ndf;
    }
    public Float getVita() {
        return this.vita;
    }
    
    public void setVita(Float vita) {
        this.vita = vita;
    }
    public Float getVite() {
        return this.vite;
    }
    
    public void setVite(Float vite) {
        this.vite = vite;
    }




}


