package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Semen generated by hbm2java
 */
@Entity
@Table(name = "semen", catalog = "induct")
public class Semen implements java.io.Serializable {

	private Integer id;
	private StatusBreed statusBreed;
	private String nameCattle;
	private String breedType;
	private String HNumber;
	private String colorCattle;
	private String tubeColor;
	private String lidColor;
	private Integer sizeId;
	private String fram;
	private String dealer;
	private Integer quantity;
	private Integer bucketId;
	private String canisterRack;
	private Set<Breeding> breedings = new HashSet<Breeding>(0);

	public Semen() {
	}

	public Semen(StatusBreed statusBreed, String nameCattle, String breedType, String HNumber, String colorCattle,
			String tubeColor, String lidColor, Integer sizeId, String fram, String dealer, Integer quantity,
			Integer bucketId, String canisterRack, Set<Breeding> breedings) {
		this.statusBreed = statusBreed;
		this.nameCattle = nameCattle;
		this.breedType = breedType;
		this.HNumber = HNumber;
		this.colorCattle = colorCattle;
		this.tubeColor = tubeColor;
		this.lidColor = lidColor;
		this.sizeId = sizeId;
		this.fram = fram;
		this.dealer = dealer;
		this.quantity = quantity;
		this.bucketId = bucketId;
		this.canisterRack = canisterRack;
		this.breedings = breedings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_breed_id")
	public StatusBreed getStatusBreed() {
		return this.statusBreed;
	}

	public void setStatusBreed(StatusBreed statusBreed) {
		this.statusBreed = statusBreed;
	}

	@Column(name = "name_cattle", length = 45)
	public String getNameCattle() {
		return this.nameCattle;
	}

	public void setNameCattle(String nameCattle) {
		this.nameCattle = nameCattle;
	}

	@Column(name = "breed_type", length = 45)
	public String getBreedType() {
		return this.breedType;
	}

	public void setBreedType(String breedType) {
		this.breedType = breedType;
	}

	@Column(name = "h_number", length = 45)
	public String getHNumber() {
		return this.HNumber;
	}

	public void setHNumber(String HNumber) {
		this.HNumber = HNumber;
	}

	@Column(name = "color_cattle", length = 45)
	public String getColorCattle() {
		return this.colorCattle;
	}

	public void setColorCattle(String colorCattle) {
		this.colorCattle = colorCattle;
	}

	@Column(name = "tube_color", length = 45)
	public String getTubeColor() {
		return this.tubeColor;
	}

	public void setTubeColor(String tubeColor) {
		this.tubeColor = tubeColor;
	}

	@Column(name = "lid_color", length = 45)
	public String getLidColor() {
		return this.lidColor;
	}

	public void setLidColor(String lidColor) {
		this.lidColor = lidColor;
	}

	@Column(name = "size_id")
	public Integer getSizeId() {
		return this.sizeId;
	}

	public void setSizeId(Integer sizeId) {
		this.sizeId = sizeId;
	}

	@Column(name = "fram", length = 45)
	public String getFram() {
		return this.fram;
	}

	public void setFram(String fram) {
		this.fram = fram;
	}

	@Column(name = "dealer", length = 45)
	public String getDealer() {
		return this.dealer;
	}

	public void setDealer(String dealer) {
		this.dealer = dealer;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "bucket_id")
	public Integer getBucketId() {
		return this.bucketId;
	}

	public void setBucketId(Integer bucketId) {
		this.bucketId = bucketId;
	}

	@Column(name = "canister_rack", length = 45)
	public String getCanisterRack() {
		return this.canisterRack;
	}

	public void setCanisterRack(String canisterRack) {
		this.canisterRack = canisterRack;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semen")
	public Set<Breeding> getBreedings() {
		return this.breedings;
	}

	public void setBreedings(Set<Breeding> breedings) {
		this.breedings = breedings;
	}

}
