// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Semen generated by hbm2java
 */
public class Semen  implements java.io.Serializable {


     private Integer id;
     private Bucket bucket;
     private Color color;
     private TypeCattle typeCattle;
     private TypeClassBeef typeClassBeef;
     private TypeClassDairy typeClassDairy;
     private String nameCattle;
     private String HNumber;
     private String colorCattle;
     private String tubeColor;
     private String lidColor;
     private String tubeSize;
     private String farm;
     private String dealer;
     private int quantity;
     private Integer canister;
     private String rack;
     private int statusalert;
     private Set breedings = new HashSet(0);
     private Set semenReleases = new HashSet(0);
     private Set semenImports = new HashSet(0);
     private Set semenOrders = new HashSet(0);

    public Semen() {
    }

	
    public Semen(int quantity, int statusalert) {
        this.quantity = quantity;
        this.statusalert = statusalert;
    }
    public Semen(Bucket bucket, Color color, TypeCattle typeCattle, TypeClassBeef typeClassBeef, TypeClassDairy typeClassDairy, String nameCattle, String HNumber, String colorCattle, String tubeColor, String lidColor, String tubeSize, String farm, String dealer, int quantity, Integer canister, String rack, int statusalert, Set breedings, Set semenReleases, Set semenImports, Set semenOrders) {
       this.bucket = bucket;
       this.color = color;
       this.typeCattle = typeCattle;
       this.typeClassBeef = typeClassBeef;
       this.typeClassDairy = typeClassDairy;
       this.nameCattle = nameCattle;
       this.HNumber = HNumber;
       this.colorCattle = colorCattle;
       this.tubeColor = tubeColor;
       this.lidColor = lidColor;
       this.tubeSize = tubeSize;
       this.farm = farm;
       this.dealer = dealer;
       this.quantity = quantity;
       this.canister = canister;
       this.rack = rack;
       this.statusalert = statusalert;
       this.breedings = breedings;
       this.semenReleases = semenReleases;
       this.semenImports = semenImports;
       this.semenOrders = semenOrders;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Bucket getBucket() {
        return this.bucket;
    }
    
    public void setBucket(Bucket bucket) {
        this.bucket = bucket;
    }
    public Color getColor() {
        return this.color;
    }
    
    public void setColor(Color color) {
        this.color = color;
    }
    public TypeCattle getTypeCattle() {
        return this.typeCattle;
    }
    
    public void setTypeCattle(TypeCattle typeCattle) {
        this.typeCattle = typeCattle;
    }
    public TypeClassBeef getTypeClassBeef() {
        return this.typeClassBeef;
    }
    
    public void setTypeClassBeef(TypeClassBeef typeClassBeef) {
        this.typeClassBeef = typeClassBeef;
    }
    public TypeClassDairy getTypeClassDairy() {
        return this.typeClassDairy;
    }
    
    public void setTypeClassDairy(TypeClassDairy typeClassDairy) {
        this.typeClassDairy = typeClassDairy;
    }
    public String getNameCattle() {
        return this.nameCattle;
    }
    
    public void setNameCattle(String nameCattle) {
        this.nameCattle = nameCattle;
    }
    public String getHNumber() {
        return this.HNumber;
    }
    
    public void setHNumber(String HNumber) {
        this.HNumber = HNumber;
    }
    public String getColorCattle() {
        return this.colorCattle;
    }
    
    public void setColorCattle(String colorCattle) {
        this.colorCattle = colorCattle;
    }
    public String getTubeColor() {
        return this.tubeColor;
    }
    
    public void setTubeColor(String tubeColor) {
        this.tubeColor = tubeColor;
    }
    public String getLidColor() {
        return this.lidColor;
    }
    
    public void setLidColor(String lidColor) {
        this.lidColor = lidColor;
    }
    public String getTubeSize() {
        return this.tubeSize;
    }
    
    public void setTubeSize(String tubeSize) {
        this.tubeSize = tubeSize;
    }
    public String getFarm() {
        return this.farm;
    }
    
    public void setFarm(String farm) {
        this.farm = farm;
    }
    public String getDealer() {
        return this.dealer;
    }
    
    public void setDealer(String dealer) {
        this.dealer = dealer;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Integer getCanister() {
        return this.canister;
    }
    
    public void setCanister(Integer canister) {
        this.canister = canister;
    }
    public String getRack() {
        return this.rack;
    }
    
    public void setRack(String rack) {
        this.rack = rack;
    }
    public int getStatusalert() {
        return this.statusalert;
    }
    
    public void setStatusalert(int statusalert) {
        this.statusalert = statusalert;
    }
    public Set getBreedings() {
        return this.breedings;
    }
    
    public void setBreedings(Set breedings) {
        this.breedings = breedings;
    }
    public Set getSemenReleases() {
        return this.semenReleases;
    }
    
    public void setSemenReleases(Set semenReleases) {
        this.semenReleases = semenReleases;
    }
    public Set getSemenImports() {
        return this.semenImports;
    }
    
    public void setSemenImports(Set semenImports) {
        this.semenImports = semenImports;
    }
    public Set getSemenOrders() {
        return this.semenOrders;
    }
    
    public void setSemenOrders(Set semenOrders) {
        this.semenOrders = semenOrders;
    }




}


