// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final



/**
 * Standard generated by hbm2java
 */
public class Standard  implements java.io.Serializable {


     private Integer id;
     private Integer startCalf1;
     private Integer startCalf2;
     private Integer startCalf3;
     private Integer endCalf1;
     private Integer endCalf2;
     private Integer endCalf3;
     private Integer startIntermediate1;
     private Integer startIntermediate2;
     private Integer startIntermediate3;
     private Integer endIntermediate1;
     private Integer endIntermediate2;
     private Integer endIntermediate3;
     private Integer startJunior1;
     private Integer startJunior2;
     private Integer startJunior3;
     private Integer endJunior1;
     private Integer endJunior2;
     private Integer endJunior3;
     private Integer startSenior1;
     private Integer startSenior2;
     private Integer startSenior3;
     private Integer endSenior1;
     private Integer endSenior2;
     private Integer endSenior3;

    public Standard() {
    }

    public Standard(Integer startCalf1, Integer startCalf2, Integer startCalf3, Integer endCalf1, Integer endCalf2, Integer endCalf3, Integer startIntermediate1, Integer startIntermediate2, Integer startIntermediate3, Integer endIntermediate1, Integer endIntermediate2, Integer endIntermediate3, Integer startJunior1, Integer startJunior2, Integer startJunior3, Integer endJunior1, Integer endJunior2, Integer endJunior3, Integer startSenior1, Integer startSenior2, Integer startSenior3, Integer endSenior1, Integer endSenior2, Integer endSenior3) {
       this.startCalf1 = startCalf1;
       this.startCalf2 = startCalf2;
       this.startCalf3 = startCalf3;
       this.endCalf1 = endCalf1;
       this.endCalf2 = endCalf2;
       this.endCalf3 = endCalf3;
       this.startIntermediate1 = startIntermediate1;
       this.startIntermediate2 = startIntermediate2;
       this.startIntermediate3 = startIntermediate3;
       this.endIntermediate1 = endIntermediate1;
       this.endIntermediate2 = endIntermediate2;
       this.endIntermediate3 = endIntermediate3;
       this.startJunior1 = startJunior1;
       this.startJunior2 = startJunior2;
       this.startJunior3 = startJunior3;
       this.endJunior1 = endJunior1;
       this.endJunior2 = endJunior2;
       this.endJunior3 = endJunior3;
       this.startSenior1 = startSenior1;
       this.startSenior2 = startSenior2;
       this.startSenior3 = startSenior3;
       this.endSenior1 = endSenior1;
       this.endSenior2 = endSenior2;
       this.endSenior3 = endSenior3;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getStartCalf1() {
        return this.startCalf1;
    }
    
    public void setStartCalf1(Integer startCalf1) {
        this.startCalf1 = startCalf1;
    }
    public Integer getStartCalf2() {
        return this.startCalf2;
    }
    
    public void setStartCalf2(Integer startCalf2) {
        this.startCalf2 = startCalf2;
    }
    public Integer getStartCalf3() {
        return this.startCalf3;
    }
    
    public void setStartCalf3(Integer startCalf3) {
        this.startCalf3 = startCalf3;
    }
    public Integer getEndCalf1() {
        return this.endCalf1;
    }
    
    public void setEndCalf1(Integer endCalf1) {
        this.endCalf1 = endCalf1;
    }
    public Integer getEndCalf2() {
        return this.endCalf2;
    }
    
    public void setEndCalf2(Integer endCalf2) {
        this.endCalf2 = endCalf2;
    }
    public Integer getEndCalf3() {
        return this.endCalf3;
    }
    
    public void setEndCalf3(Integer endCalf3) {
        this.endCalf3 = endCalf3;
    }
    public Integer getStartIntermediate1() {
        return this.startIntermediate1;
    }
    
    public void setStartIntermediate1(Integer startIntermediate1) {
        this.startIntermediate1 = startIntermediate1;
    }
    public Integer getStartIntermediate2() {
        return this.startIntermediate2;
    }
    
    public void setStartIntermediate2(Integer startIntermediate2) {
        this.startIntermediate2 = startIntermediate2;
    }
    public Integer getStartIntermediate3() {
        return this.startIntermediate3;
    }
    
    public void setStartIntermediate3(Integer startIntermediate3) {
        this.startIntermediate3 = startIntermediate3;
    }
    public Integer getEndIntermediate1() {
        return this.endIntermediate1;
    }
    
    public void setEndIntermediate1(Integer endIntermediate1) {
        this.endIntermediate1 = endIntermediate1;
    }
    public Integer getEndIntermediate2() {
        return this.endIntermediate2;
    }
    
    public void setEndIntermediate2(Integer endIntermediate2) {
        this.endIntermediate2 = endIntermediate2;
    }
    public Integer getEndIntermediate3() {
        return this.endIntermediate3;
    }
    
    public void setEndIntermediate3(Integer endIntermediate3) {
        this.endIntermediate3 = endIntermediate3;
    }
    public Integer getStartJunior1() {
        return this.startJunior1;
    }
    
    public void setStartJunior1(Integer startJunior1) {
        this.startJunior1 = startJunior1;
    }
    public Integer getStartJunior2() {
        return this.startJunior2;
    }
    
    public void setStartJunior2(Integer startJunior2) {
        this.startJunior2 = startJunior2;
    }
    public Integer getStartJunior3() {
        return this.startJunior3;
    }
    
    public void setStartJunior3(Integer startJunior3) {
        this.startJunior3 = startJunior3;
    }
    public Integer getEndJunior1() {
        return this.endJunior1;
    }
    
    public void setEndJunior1(Integer endJunior1) {
        this.endJunior1 = endJunior1;
    }
    public Integer getEndJunior2() {
        return this.endJunior2;
    }
    
    public void setEndJunior2(Integer endJunior2) {
        this.endJunior2 = endJunior2;
    }
    public Integer getEndJunior3() {
        return this.endJunior3;
    }
    
    public void setEndJunior3(Integer endJunior3) {
        this.endJunior3 = endJunior3;
    }
    public Integer getStartSenior1() {
        return this.startSenior1;
    }
    
    public void setStartSenior1(Integer startSenior1) {
        this.startSenior1 = startSenior1;
    }
    public Integer getStartSenior2() {
        return this.startSenior2;
    }
    
    public void setStartSenior2(Integer startSenior2) {
        this.startSenior2 = startSenior2;
    }
    public Integer getStartSenior3() {
        return this.startSenior3;
    }
    
    public void setStartSenior3(Integer startSenior3) {
        this.startSenior3 = startSenior3;
    }
    public Integer getEndSenior1() {
        return this.endSenior1;
    }
    
    public void setEndSenior1(Integer endSenior1) {
        this.endSenior1 = endSenior1;
    }
    public Integer getEndSenior2() {
        return this.endSenior2;
    }
    
    public void setEndSenior2(Integer endSenior2) {
        this.endSenior2 = endSenior2;
    }
    public Integer getEndSenior3() {
        return this.endSenior3;
    }
    
    public void setEndSenior3(Integer endSenior3) {
        this.endSenior3 = endSenior3;
    }




}


