package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StatusTreat generated by hbm2java
 */
@Entity
@Table(name = "status_treat", catalog = "induct")
public class StatusTreat implements java.io.Serializable {

	private Integer id;
	private String status;
	private Set<TreatmentHistory> treatmentHistories = new HashSet<TreatmentHistory>(0);
	private Set<Cattle> cattles = new HashSet<Cattle>(0);

	public StatusTreat() {
	}

	public StatusTreat(String status, Set<TreatmentHistory> treatmentHistories, Set<Cattle> cattles) {
		this.status = status;
		this.treatmentHistories = treatmentHistories;
		this.cattles = cattles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusTreat")
	public Set<TreatmentHistory> getTreatmentHistories() {
		return this.treatmentHistories;
	}

	public void setTreatmentHistories(Set<TreatmentHistory> treatmentHistories) {
		this.treatmentHistories = treatmentHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusTreat")
	public Set<Cattle> getCattles() {
		return this.cattles;
	}

	public void setCattles(Set<Cattle> cattles) {
		this.cattles = cattles;
	}

}
