// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * StatusAlert generated by hbm2java
 */
public class StatusAlert  implements java.io.Serializable {


     private Integer id;
     private String value;
     private Set alerts = new HashSet(0);

    public StatusAlert() {
    }

	
    public StatusAlert(String value) {
        this.value = value;
    }
    public StatusAlert(String value, Set alerts) {
       this.value = value;
       this.alerts = alerts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set getAlerts() {
        return this.alerts;
    }
    
    public void setAlerts(Set alerts) {
        this.alerts = alerts;
    }




}


