package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StatusPregnant generated by hbm2java
 */
@Entity
@Table(name = "status_pregnant", catalog = "induct")
public class StatusPregnant implements java.io.Serializable {

	private Integer id;
	private String value;
	private Set<Pregnant> pregnants = new HashSet<Pregnant>(0);

	public StatusPregnant() {
	}

	public StatusPregnant(String value, Set<Pregnant> pregnants) {
		this.value = value;
		this.pregnants = pregnants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "value", length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusPregnant")
	public Set<Pregnant> getPregnants() {
		return this.pregnants;
	}

	public void setPregnants(Set<Pregnant> pregnants) {
		this.pregnants = pregnants;
	}

}
