// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private Integer id;
     private String value;
     private Set toolBrokens = new HashSet(0);
     private Set toolBorrows = new HashSet(0);

    public Status() {
    }

	
    public Status(String value) {
        this.value = value;
    }
    public Status(String value, Set toolBrokens, Set toolBorrows) {
       this.value = value;
       this.toolBrokens = toolBrokens;
       this.toolBorrows = toolBorrows;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set getToolBrokens() {
        return this.toolBrokens;
    }
    
    public void setToolBrokens(Set toolBrokens) {
        this.toolBrokens = toolBrokens;
    }
    public Set getToolBorrows() {
        return this.toolBorrows;
    }
    
    public void setToolBorrows(Set toolBorrows) {
        this.toolBorrows = toolBorrows;
    }




}


