package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sync generated by hbm2java
 */
@Entity
@Table(name = "sync", catalog = "induct")
public class Sync implements java.io.Serializable {

	private Integer id;
	private TypeSync typeSync;
	private String namesync;
	private Integer dayalert;
	private String timealert;

	public Sync() {
	}

	public Sync(TypeSync typeSync, String namesync, Integer dayalert, String timealert) {
		this.typeSync = typeSync;
		this.namesync = namesync;
		this.dayalert = dayalert;
		this.timealert = timealert;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_sync_id")
	public TypeSync getTypeSync() {
		return this.typeSync;
	}

	public void setTypeSync(TypeSync typeSync) {
		this.typeSync = typeSync;
	}

	@Column(name = "namesync", length = 45)
	public String getNamesync() {
		return this.namesync;
	}

	public void setNamesync(String namesync) {
		this.namesync = namesync;
	}

	@Column(name = "dayalert")
	public Integer getDayalert() {
		return this.dayalert;
	}

	public void setDayalert(Integer dayalert) {
		this.dayalert = dayalert;
	}

	@Column(name = "timealert", length = 50)
	public String getTimealert() {
		return this.timealert;
	}

	public void setTimealert(String timealert) {
		this.timealert = timealert;
	}

}
