// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * Synchronize generated by hbm2java
 */
public class Synchronize  implements java.io.Serializable {


     private Integer id;
     private Cattle cattle;
     private Member member;
     private TypeSync typeSync;
     private Date dateSync;

    public Synchronize() {
    }

    public Synchronize(Cattle cattle, Member member, TypeSync typeSync, Date dateSync) {
       this.cattle = cattle;
       this.member = member;
       this.typeSync = typeSync;
       this.dateSync = dateSync;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cattle getCattle() {
        return this.cattle;
    }
    
    public void setCattle(Cattle cattle) {
        this.cattle = cattle;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public TypeSync getTypeSync() {
        return this.typeSync;
    }
    
    public void setTypeSync(TypeSync typeSync) {
        this.typeSync = typeSync;
    }
    public Date getDateSync() {
        return this.dateSync;
    }
    
    public void setDateSync(Date dateSync) {
        this.dateSync = dateSync;
    }




}


