// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final



/**
 * Sync generated by hbm2java
 */
public class Sync  implements java.io.Serializable {


     private Integer id;
     private TypeSync typeSync;
     private String namesync;
     private Integer dayalert;
     private String timealert;

    public Sync() {
    }

    public Sync(TypeSync typeSync, String namesync, Integer dayalert, String timealert) {
       this.typeSync = typeSync;
       this.namesync = namesync;
       this.dayalert = dayalert;
       this.timealert = timealert;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TypeSync getTypeSync() {
        return this.typeSync;
    }
    
    public void setTypeSync(TypeSync typeSync) {
        this.typeSync = typeSync;
    }
    public String getNamesync() {
        return this.namesync;
    }
    
    public void setNamesync(String namesync) {
        this.namesync = namesync;
    }
    public Integer getDayalert() {
        return this.dayalert;
    }
    
    public void setDayalert(Integer dayalert) {
        this.dayalert = dayalert;
    }
    public String getTimealert() {
        return this.timealert;
    }
    
    public void setTimealert(String timealert) {
        this.timealert = timealert;
    }




}


