// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * ToolBroken generated by hbm2java
 */
public class ToolBroken  implements java.io.Serializable {


     private Integer id;
     private Bill bill;
     private Member member;
     private Status status;
     private Tool tool;
     private Integer quantity;
     private Date dayBroken;
     private Date dayReturn;

    public ToolBroken() {
    }

    public ToolBroken(Bill bill, Member member, Status status, Tool tool, Integer quantity, Date dayBroken, Date dayReturn) {
       this.bill = bill;
       this.member = member;
       this.status = status;
       this.tool = tool;
       this.quantity = quantity;
       this.dayBroken = dayBroken;
       this.dayReturn = dayReturn;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Bill getBill() {
        return this.bill;
    }
    
    public void setBill(Bill bill) {
        this.bill = bill;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public Tool getTool() {
        return this.tool;
    }
    
    public void setTool(Tool tool) {
        this.tool = tool;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Date getDayBroken() {
        return this.dayBroken;
    }
    
    public void setDayBroken(Date dayBroken) {
        this.dayBroken = dayBroken;
    }
    public Date getDayReturn() {
        return this.dayReturn;
    }
    
    public void setDayReturn(Date dayReturn) {
        this.dayReturn = dayReturn;
    }




}


