// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Tool generated by hbm2java
 */
public class Tool  implements java.io.Serializable {


     private Integer id;
     private TypeTool typeTool;
     private UnitTool unitTool;
     private String name;
     private Integer quantity;
     private Integer quantityBorrow;
     private Integer quantityBroken;
     private String place;
     private int statusalert;
     private Set toolImports = new HashSet(0);
     private Set toolOrders = new HashSet(0);
     private Set toolReleases = new HashSet(0);
     private Set toolBorrows = new HashSet(0);
     private Set toolBrokens = new HashSet(0);

    public Tool() {
    }

	
    public Tool(TypeTool typeTool, UnitTool unitTool, int statusalert) {
        this.typeTool = typeTool;
        this.unitTool = unitTool;
        this.statusalert = statusalert;
    }
    public Tool(TypeTool typeTool, UnitTool unitTool, String name, Integer quantity, Integer quantityBorrow, Integer quantityBroken, String place, int statusalert, Set toolImports, Set toolOrders, Set toolReleases, Set toolBorrows, Set toolBrokens) {
       this.typeTool = typeTool;
       this.unitTool = unitTool;
       this.name = name;
       this.quantity = quantity;
       this.quantityBorrow = quantityBorrow;
       this.quantityBroken = quantityBroken;
       this.place = place;
       this.statusalert = statusalert;
       this.toolImports = toolImports;
       this.toolOrders = toolOrders;
       this.toolReleases = toolReleases;
       this.toolBorrows = toolBorrows;
       this.toolBrokens = toolBrokens;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TypeTool getTypeTool() {
        return this.typeTool;
    }
    
    public void setTypeTool(TypeTool typeTool) {
        this.typeTool = typeTool;
    }
    public UnitTool getUnitTool() {
        return this.unitTool;
    }
    
    public void setUnitTool(UnitTool unitTool) {
        this.unitTool = unitTool;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Integer getQuantityBorrow() {
        return this.quantityBorrow;
    }
    
    public void setQuantityBorrow(Integer quantityBorrow) {
        this.quantityBorrow = quantityBorrow;
    }
    public Integer getQuantityBroken() {
        return this.quantityBroken;
    }
    
    public void setQuantityBroken(Integer quantityBroken) {
        this.quantityBroken = quantityBroken;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    public int getStatusalert() {
        return this.statusalert;
    }
    
    public void setStatusalert(int statusalert) {
        this.statusalert = statusalert;
    }
    public Set getToolImports() {
        return this.toolImports;
    }
    
    public void setToolImports(Set toolImports) {
        this.toolImports = toolImports;
    }
    public Set getToolOrders() {
        return this.toolOrders;
    }
    
    public void setToolOrders(Set toolOrders) {
        this.toolOrders = toolOrders;
    }
    public Set getToolReleases() {
        return this.toolReleases;
    }
    
    public void setToolReleases(Set toolReleases) {
        this.toolReleases = toolReleases;
    }
    public Set getToolBorrows() {
        return this.toolBorrows;
    }
    
    public void setToolBorrows(Set toolBorrows) {
        this.toolBorrows = toolBorrows;
    }
    public Set getToolBrokens() {
        return this.toolBrokens;
    }
    
    public void setToolBrokens(Set toolBrokens) {
        this.toolBrokens = toolBrokens;
    }




}


