// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * ToolBorrow generated by hbm2java
 */
public class ToolBorrow  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private Status status;
     private Tool tool;
     private Integer quantity;
     private Date dayBorrow;
     private Date dayReturn;
     private Integer billId;

    public ToolBorrow() {
    }

    public ToolBorrow(Member member, Status status, Tool tool, Integer quantity, Date dayBorrow, Date dayReturn, Integer billId) {
       this.member = member;
       this.status = status;
       this.tool = tool;
       this.quantity = quantity;
       this.dayBorrow = dayBorrow;
       this.dayReturn = dayReturn;
       this.billId = billId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public Tool getTool() {
        return this.tool;
    }
    
    public void setTool(Tool tool) {
        this.tool = tool;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Date getDayBorrow() {
        return this.dayBorrow;
    }
    
    public void setDayBorrow(Date dayBorrow) {
        this.dayBorrow = dayBorrow;
    }
    public Date getDayReturn() {
        return this.dayReturn;
    }
    
    public void setDayReturn(Date dayReturn) {
        this.dayReturn = dayReturn;
    }
    public Integer getBillId() {
        return this.billId;
    }
    
    public void setBillId(Integer billId) {
        this.billId = billId;
    }




}


