package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TreatmentHistory generated by hbm2java
 */
@Entity
@Table(name = "treatment_history", catalog = "induct")
public class TreatmentHistory implements java.io.Serializable {

	private Integer id;
	private Cattle cattle;
	private StatusTreat statusTreat;
	private StatusDisease statusDisease;
	private Member member;
	private Disease disease;
	private Medicine medicine;
	private StatusMedicine statusMedicine;
	private String symptom;
	private String causeOfIllness;
	private String beAllergic;
	private String dateTreat;
	private String dateEndTreat;
	private Integer doseUsesage;
	private String dateStartMed;
	private String dateStopMed;
	private String note;

	public TreatmentHistory() {
	}

	public TreatmentHistory(Cattle cattle, StatusTreat statusTreat, StatusDisease statusDisease, Member member,
			Disease disease, Medicine medicine, StatusMedicine statusMedicine, String symptom, String causeOfIllness,
			String beAllergic, String dateTreat, String dateEndTreat, Integer doseUsesage, String dateStartMed,
			String dateStopMed, String note) {
		this.cattle = cattle;
		this.statusTreat = statusTreat;
		this.statusDisease = statusDisease;
		this.member = member;
		this.disease = disease;
		this.medicine = medicine;
		this.statusMedicine = statusMedicine;
		this.symptom = symptom;
		this.causeOfIllness = causeOfIllness;
		this.beAllergic = beAllergic;
		this.dateTreat = dateTreat;
		this.dateEndTreat = dateEndTreat;
		this.doseUsesage = doseUsesage;
		this.dateStartMed = dateStartMed;
		this.dateStopMed = dateStopMed;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cattle_id")
	public Cattle getCattle() {
		return this.cattle;
	}

	public void setCattle(Cattle cattle) {
		this.cattle = cattle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_treat_id")
	public StatusTreat getStatusTreat() {
		return this.statusTreat;
	}

	public void setStatusTreat(StatusTreat statusTreat) {
		this.statusTreat = statusTreat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_disease")
	public StatusDisease getStatusDisease() {
		return this.statusDisease;
	}

	public void setStatusDisease(StatusDisease statusDisease) {
		this.statusDisease = statusDisease;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "select_disease")
	public Disease getDisease() {
		return this.disease;
	}

	public void setDisease(Disease disease) {
		this.disease = disease;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "select_medicine")
	public Medicine getMedicine() {
		return this.medicine;
	}

	public void setMedicine(Medicine medicine) {
		this.medicine = medicine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_medicine")
	public StatusMedicine getStatusMedicine() {
		return this.statusMedicine;
	}

	public void setStatusMedicine(StatusMedicine statusMedicine) {
		this.statusMedicine = statusMedicine;
	}

	@Column(name = "symptom", length = 400)
	public String getSymptom() {
		return this.symptom;
	}

	public void setSymptom(String symptom) {
		this.symptom = symptom;
	}

	@Column(name = "cause_of_illness", length = 400)
	public String getCauseOfIllness() {
		return this.causeOfIllness;
	}

	public void setCauseOfIllness(String causeOfIllness) {
		this.causeOfIllness = causeOfIllness;
	}

	@Column(name = "be_allergic", length = 400)
	public String getBeAllergic() {
		return this.beAllergic;
	}

	public void setBeAllergic(String beAllergic) {
		this.beAllergic = beAllergic;
	}


	@Column(name = "date_treat", length = 10)
	public String getDateTreat() {
		return this.dateTreat;
	}

	public void setDateTreat(String dateTreat) {
		this.dateTreat = dateTreat;
	}

	@Column(name = "date_end_treat", length = 8)
	public String getDateEndTreat() {
		return this.dateEndTreat;
	}

	public void setDateEndTreat(String dateEndTreat) {
		this.dateEndTreat = dateEndTreat;
	}

	@Column(name = "dose_usesage")
	public Integer getDoseUsesage() {
		return this.doseUsesage;
	}

	public void setDoseUsesage(Integer doseUsesage) {
		this.doseUsesage = doseUsesage;
	}


	@Column(name = "date_start_med", length = 10)
	public String getDateStartMed() {
		return this.dateStartMed;
	}

	public void setDateStartMed(String dateStartMed) {
		this.dateStartMed = dateStartMed;
	}


	@Column(name = "date_stop_med", length = 10)
	public String getDateStopMed() {
		return this.dateStopMed;
	}

	public void setDateStopMed(String dateStopMed) {
		this.dateStopMed = dateStopMed;
	}

	@Column(name = "note", length = 400)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
