// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * TypeBucket generated by hbm2java
 */
public class TypeBucket  implements java.io.Serializable {


     private Integer id;
     private String value;
     private Set buckets = new HashSet(0);

    public TypeBucket() {
    }

    public TypeBucket(String value, Set buckets) {
       this.value = value;
       this.buckets = buckets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set getBuckets() {
        return this.buckets;
    }
    
    public void setBuckets(Set buckets) {
        this.buckets = buckets;
    }




}


