// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * TypeAlert generated by hbm2java
 */
public class TypeAlert  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer value;
     private String note;
     private Set alerts = new HashSet(0);

    public TypeAlert() {
    }

    public TypeAlert(String name, Integer value, String note, Set alerts) {
       this.name = name;
       this.value = value;
       this.note = note;
       this.alerts = alerts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getValue() {
        return this.value;
    }
    
    public void setValue(Integer value) {
        this.value = value;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Set getAlerts() {
        return this.alerts;
    }
    
    public void setAlerts(Set alerts) {
        this.alerts = alerts;
    }




}


