package healthcares.spring.model;
// Generated Aug 3, 2016 3:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeSync generated by hbm2java
 */
@Entity
@Table(name = "type_sync", catalog = "induct")
public class TypeSync implements java.io.Serializable {

	private Integer id;
	private String value;
	private Set<Synchronize> synchronizes = new HashSet<Synchronize>(0);
	private Set<Sync> syncs = new HashSet<Sync>(0);

	public TypeSync() {
	}

	public TypeSync(String value, Set<Synchronize> synchronizes, Set<Sync> syncs) {
		this.value = value;
		this.synchronizes = synchronizes;
		this.syncs = syncs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "value", length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeSync")
	public Set<Synchronize> getSynchronizes() {
		return this.synchronizes;
	}

	public void setSynchronizes(Set<Synchronize> synchronizes) {
		this.synchronizes = synchronizes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeSync")
	public Set<Sync> getSyncs() {
		return this.syncs;
	}

	public void setSyncs(Set<Sync> syncs) {
		this.syncs = syncs;
	}

}
