// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * TypeClassDairy generated by hbm2java
 */
public class TypeClassDairy  implements java.io.Serializable {


     private Integer id;
     private String dairy;
     private Set semens = new HashSet(0);
     private Set cattleStrains = new HashSet(0);
     private Set cattlePedigrees = new HashSet(0);

    public TypeClassDairy() {
    }

	
    public TypeClassDairy(String dairy) {
        this.dairy = dairy;
    }
    public TypeClassDairy(String dairy, Set semens, Set cattleStrains, Set cattlePedigrees) {
       this.dairy = dairy;
       this.semens = semens;
       this.cattleStrains = cattleStrains;
       this.cattlePedigrees = cattlePedigrees;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDairy() {
        return this.dairy;
    }
    
    public void setDairy(String dairy) {
        this.dairy = dairy;
    }
    public Set getSemens() {
        return this.semens;
    }
    
    public void setSemens(Set semens) {
        this.semens = semens;
    }
    public Set getCattleStrains() {
        return this.cattleStrains;
    }
    
    public void setCattleStrains(Set cattleStrains) {
        this.cattleStrains = cattleStrains;
    }
    public Set getCattlePedigrees() {
        return this.cattlePedigrees;
    }
    
    public void setCattlePedigrees(Set cattlePedigrees) {
        this.cattlePedigrees = cattlePedigrees;
    }




}


