// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set festivities = new HashSet(0);

    public Type() {
    }

    public Type(String name, Set festivities) {
       this.name = name;
       this.festivities = festivities;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getFestivities() {
        return this.festivities;
    }
    
    public void setFestivities(Set festivities) {
        this.festivities = festivities;
    }




}


