// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * TypeCattle generated by hbm2java
 */
public class TypeCattle  implements java.io.Serializable {


     private Integer id;
     private String value;
     private Set cattles = new HashSet(0);
     private Set semens = new HashSet(0);
     private Set cattleStrains = new HashSet(0);
     private Set cattlePedigrees = new HashSet(0);

    public TypeCattle() {
    }

    public TypeCattle(String value, Set cattles, Set semens, Set cattleStrains, Set cattlePedigrees) {
       this.value = value;
       this.cattles = cattles;
       this.semens = semens;
       this.cattleStrains = cattleStrains;
       this.cattlePedigrees = cattlePedigrees;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set getCattles() {
        return this.cattles;
    }
    
    public void setCattles(Set cattles) {
        this.cattles = cattles;
    }
    public Set getSemens() {
        return this.semens;
    }
    
    public void setSemens(Set semens) {
        this.semens = semens;
    }
    public Set getCattleStrains() {
        return this.cattleStrains;
    }
    
    public void setCattleStrains(Set cattleStrains) {
        this.cattleStrains = cattleStrains;
    }
    public Set getCattlePedigrees() {
        return this.cattlePedigrees;
    }
    
    public void setCattlePedigrees(Set cattlePedigrees) {
        this.cattlePedigrees = cattlePedigrees;
    }




}


