// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * TypeClassBeef generated by hbm2java
 */
public class TypeClassBeef  implements java.io.Serializable {


     private Integer id;
     private String breeds;
     private Set cattleStrains = new HashSet(0);
     private Set cattlePedigrees = new HashSet(0);
     private Set cattles = new HashSet(0);
     private Set semens = new HashSet(0);

    public TypeClassBeef() {
    }

    public TypeClassBeef(String breeds, Set cattleStrains, Set cattlePedigrees, Set cattles, Set semens) {
       this.breeds = breeds;
       this.cattleStrains = cattleStrains;
       this.cattlePedigrees = cattlePedigrees;
       this.cattles = cattles;
       this.semens = semens;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getBreeds() {
        return this.breeds;
    }
    
    public void setBreeds(String breeds) {
        this.breeds = breeds;
    }
    public Set getCattleStrains() {
        return this.cattleStrains;
    }
    
    public void setCattleStrains(Set cattleStrains) {
        this.cattleStrains = cattleStrains;
    }
    public Set getCattlePedigrees() {
        return this.cattlePedigrees;
    }
    
    public void setCattlePedigrees(Set cattlePedigrees) {
        this.cattlePedigrees = cattlePedigrees;
    }
    public Set getCattles() {
        return this.cattles;
    }
    
    public void setCattles(Set cattles) {
        this.cattles = cattles;
    }
    public Set getSemens() {
        return this.semens;
    }
    
    public void setSemens(Set semens) {
        this.semens = semens;
    }




}


