// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * TypeFormula generated by hbm2java
 */
public class TypeFormula  implements java.io.Serializable {


     private Integer id;
     private String value;
     private Set formulaRecords = new HashSet(0);
     private Set formulaRecord2s = new HashSet(0);

    public TypeFormula() {
    }

	
    public TypeFormula(String value) {
        this.value = value;
    }
    public TypeFormula(String value, Set formulaRecords, Set formulaRecord2s) {
       this.value = value;
       this.formulaRecords = formulaRecords;
       this.formulaRecord2s = formulaRecord2s;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set getFormulaRecords() {
        return this.formulaRecords;
    }
    
    public void setFormulaRecords(Set formulaRecords) {
        this.formulaRecords = formulaRecords;
    }
    public Set getFormulaRecord2s() {
        return this.formulaRecord2s;
    }
    
    public void setFormulaRecord2s(Set formulaRecord2s) {
        this.formulaRecord2s = formulaRecord2s;
    }




}


