// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * UnitTool generated by hbm2java
 */
public class UnitTool  implements java.io.Serializable {


     private Integer id;
     private String value;
     private Set tools = new HashSet(0);

    public UnitTool() {
    }

    public UnitTool(String value, Set tools) {
       this.value = value;
       this.tools = tools;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set getTools() {
        return this.tools;
    }
    
    public void setTools(Set tools) {
        this.tools = tools;
    }




}


