// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String fristName;
     private String lastName;
     private String address;
     private String thaiId;

    public Users() {
    }

    public Users(String fristName, String lastName, String address, String thaiId) {
       this.fristName = fristName;
       this.lastName = lastName;
       this.address = address;
       this.thaiId = thaiId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFristName() {
        return this.fristName;
    }
    
    public void setFristName(String fristName) {
        this.fristName = fristName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getThaiId() {
        return this.thaiId;
    }
    
    public void setThaiId(String thaiId) {
        this.thaiId = thaiId;
    }




}


