// default package
// Generated Dec 11, 2017 7:32:01 PM by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Worktogether generated by hbm2java
 */
public class Worktogether  implements java.io.Serializable {


     private Integer id;
     private Festivity festivity;
     private String name;
     private String surname;
     private String idcard;
     private String address;
     private Set pays = new HashSet(0);
     private Set reports = new HashSet(0);

    public Worktogether() {
    }

    public Worktogether(Festivity festivity, String name, String surname, String idcard, String address, Set pays, Set reports) {
       this.festivity = festivity;
       this.name = name;
       this.surname = surname;
       this.idcard = idcard;
       this.address = address;
       this.pays = pays;
       this.reports = reports;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Festivity getFestivity() {
        return this.festivity;
    }
    
    public void setFestivity(Festivity festivity) {
        this.festivity = festivity;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getIdcard() {
        return this.idcard;
    }
    
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set getPays() {
        return this.pays;
    }
    
    public void setPays(Set pays) {
        this.pays = pays;
    }
    public Set getReports() {
        return this.reports;
    }
    
    public void setReports(Set reports) {
        this.reports = reports;
    }




}


